<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add new Claim_cancelActionButton</name>
   <tag></tag>
   <elementGuidId>08ef53c1-d784-46a7-8fea-8253bfba9686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cancelActionButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cancelActionButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b8a6f1a-8fde-476a-8c32-e7fbe007a5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancelActionButton</value>
      <webElementGuid>0ab19e6b-2ba4-4015-88f8-4a08b739c053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76ef2671-18c8-4847-a677-1336cf1857a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NO</value>
      <webElementGuid>67a4d7e6-0dcd-47ba-8021-687e7a7b9429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button</value>
      <webElementGuid>f17aaa83-acd2-4adc-8f86-814ce7ddf941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancelActionButton&quot;)</value>
      <webElementGuid>4a5eccb7-667e-4b13-932c-f3a400ce8a0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cancelActionButton']</value>
      <webElementGuid>470af00b-dafc-4675-89cc-9358bd0c2722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='confirmActionWindow']/p/input[2]</value>
      <webElementGuid>d90552d9-8921-480e-961a-c56d03ae909e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p/input[2]</value>
      <webElementGuid>3d5993f0-d6d0-4d76-a024-6f935658d7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cancelActionButton' and @type = 'button']</value>
      <webElementGuid>bc31b2e8-1c8a-4936-a7db-387fcb292153</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
