<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Mark as Complete and Ready for Submission</name>
   <tag></tag>
   <elementGuidId>db99991f-51c3-4247-9e9d-831c98b4a8b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='linkedClaim']/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.k-checkbox-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4a8a92eb-0d81-4cdd-a2c6-87f53833e8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-checkbox-label</value>
      <webElementGuid>10ac1c71-f9ff-481c-9b92-03bc2e641400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>IsComplete</value>
      <webElementGuid>c3e1bba7-f974-4fdf-86fd-1b81871aa548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mark as Complete and Ready for Submission</value>
      <webElementGuid>b4e09c23-05fa-425d-8404-90342c022df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;linkedClaim&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/label[@class=&quot;k-checkbox-label&quot;]</value>
      <webElementGuid>4fcfa68f-feb9-4993-846e-45bac4c8fcf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='linkedClaim']/div/div/label</value>
      <webElementGuid>bda882d4-7325-4d85-8591-e128f5c39d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete and Ready for submission'])[2]/following::label[1]</value>
      <webElementGuid>45f15723-6d9e-40b2-9ee0-379222d22078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete and Ready for submission'])[1]/following::label[1]</value>
      <webElementGuid>abc9e8f6-b8a7-44d2-8d2e-9cc30febaa89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eurolink Network International Corporation'])[1]/preceding::label[1]</value>
      <webElementGuid>73cd1559-44ce-429d-a857-72a8a35e77bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mark as Complete and Ready for Submission']/parent::*</value>
      <webElementGuid>9ae88d59-25f7-4cf5-bc70-1126bd3553bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>496555df-5768-4e06-9f5f-3ef374bcc705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Mark as Complete and Ready for Submission' or . = 'Mark as Complete and Ready for Submission')]</value>
      <webElementGuid>af08a5c9-41ec-4eee-a4b6-76bc58698aee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
