<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DDT-Testing</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>10fe2d81-43c9-40e8-a48e-75271eeb1252</testSuiteGuid>
   <testCaseLink>
      <guid>ba3aae8c-d37f-4b64-9fdf-c1fc66ae7311</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data-Driven Testing/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c5a01460-3cfe-41d6-a4dd-4f05d0439bd5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/5 Accounts Data Internal</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c5a01460-3cfe-41d6-a4dd-4f05d0439bd5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>34a2946d-edce-4a4c-939d-364c2d9fe04f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c5a01460-3cfe-41d6-a4dd-4f05d0439bd5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>917a6d31-7363-46a7-8322-1539870f9eee</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
