<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Consumption_EnoughBenefitsEsoa_Defaul_ded43e</name>
   <tag></tag>
   <elementGuidId>242f1f8d-c40e-41cc-b0b5-e1e6b27acdb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Consumption_EnoughBenefitsEsoa_Y']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Consumption_EnoughBenefitsEsoa_Y</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9c5d0e6-98d8-4262-85c9-1f000f817142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-radio consumptionEnoughBenefits</value>
      <webElementGuid>357ea2a3-b911-4581-b32c-cedeeebdb146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d7d5d564-30b5-436a-8889-505a7d4a9def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Consumption_EnoughBenefitsEsoa_Y</value>
      <webElementGuid>967a035d-a8d4-45e1-995b-36cc9f9e6d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Consumption.EnoughBenefitsEsoa</value>
      <webElementGuid>7a77160d-5422-4741-95b6-ec5b96d54fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ESOA_enoughBenefits_change()</value>
      <webElementGuid>2b75f540-de1e-44e9-9fca-26b44413223f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b4cd0eda-70ea-4016-8ef4-8c9c3b939345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>72fce35c-7ad7-4e48-9ca8-f821c4ac9437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Consumption_EnoughBenefitsEsoa_Y&quot;)</value>
      <webElementGuid>6cc6271d-ce0a-44d8-a0a1-0e59278cbf7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Consumption_EnoughBenefitsEsoa_Y']</value>
      <webElementGuid>68e4152a-d12b-42fd-b6a6-711e75367569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='enoughbenefitsForm']/div/div/div/input[2]</value>
      <webElementGuid>88059b80-3557-4478-91d6-471f28961e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/input[2]</value>
      <webElementGuid>afd5997c-3be2-42ac-ba9c-a0125bd69006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Consumption_EnoughBenefitsEsoa_Y' and @name = 'Consumption.EnoughBenefitsEsoa' and @type = 'radio']</value>
      <webElementGuid>f74ffc40-ac13-4622-9f95-2d49c4d65df0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
