<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Name_ItemName</name>
   <tag></tag>
   <elementGuidId>82531f81-848c-44f1-9046-6f33309b7372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ItemName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ItemName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9f50430-9e44-4a7e-9947-c7c9ff0492b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ItemName</value>
      <webElementGuid>7eced0a3-aaa0-41a5-8316-efa792e52d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-textbox input-name</value>
      <webElementGuid>604037d0-1b26-4ade-94a7-d2a58583c8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value:ItemName</value>
      <webElementGuid>c9e1697c-d396-4aa4-8533-967fb1abbed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required-msg</name>
      <type>Main</type>
      <value>Item Name field is required.</value>
      <webElementGuid>3a1de701-b440-4680-830f-511a0578a49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f3dfaa4e-8c7a-493d-ae9c-60276601564b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;k-webkit k-webkit130 js&quot;]/body[@class=&quot;k-content&quot;]/div[@class=&quot;k-widget k-window&quot;]/div[@class=&quot;k-popup-edit-form k-window-content&quot;]/div[@class=&quot;k-edit-form-container&quot;]/div[@class=&quot;k-edit-field&quot;]/input[@class=&quot;k-textbox input-name&quot;]</value>
      <webElementGuid>ed9fbfad-7c5d-4d46-9089-2f70ea37bef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ItemName']</value>
      <webElementGuid>d2abc96b-301f-4ba2-bb6c-89c01b0d6d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>0fd0adef-9af1-4c91-911a-393b4b319376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ItemName']</value>
      <webElementGuid>821b2ac8-96a6-4110-80c8-db2418f42ccf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
