<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit Price_UnitPrice</name>
   <tag></tag>
   <elementGuidId>218f9d45-5b8e-437a-8f56-064d7ad0dce9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UnitPrice']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#UnitPrice</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c2c1563-3051-47cc-9f85-1b09348f6bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>142f61c0-6d1b-4971-b591-81e2819b000c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UnitPrice</value>
      <webElementGuid>4b67ce64-82aa-4211-8338-e013cd845e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UnitPrice</value>
      <webElementGuid>fd27f77c-5b7e-4e6d-b71d-868ecd200e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Unit Price</value>
      <webElementGuid>32ae48bf-9d0d-44f3-8560-f31af624cd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>4c6575f9-acf4-4c13-b6fe-fc441fd8eee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3adf8a36-e0cd-4edd-b771-a4393f1a80fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8510fa77-1dd5-467f-abd1-1f8587ddf7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>99999999.99</value>
      <webElementGuid>13be08ba-73b2-4385-9a38-9c8286f01226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>32acb4b9-725c-49d1-8d6f-a23e02b0a1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value:UnitPrice</value>
      <webElementGuid>7cb7032b-ee41-4d93-9db9-7a9e2d750dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>numerictextbox</value>
      <webElementGuid>31c40d95-5b62-4ce3-94fc-8bbcc321e2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>2970585e-48a1-49e7-ab13-4b8e8decfefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5a21d611-dc1d-48ee-a681-1735e3bd953c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>99999999.99</value>
      <webElementGuid>18e1c7ec-41ef-4b03-8279-8e4d4b04f7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>41666e80-893e-4374-9852-e182e8848e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>980059ae-76a4-4164-9847-cfc637b2995a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>592e0c6a-5ab2-4307-9733-d6b5bd0c0994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required-msg</name>
      <type>Main</type>
      <value>Unit Price field is required.</value>
      <webElementGuid>b72c3e4e-7ef4-40bb-a00f-878b09c432e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>itemizeOnFocusUnitPrice(this)</value>
      <webElementGuid>ad019a48-0265-41a4-a4e9-b0c373479b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>itemizeOnChange(this)</value>
      <webElementGuid>88445283-fdc0-4cc9-bfdf-83aad4cf685a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UnitPrice&quot;)</value>
      <webElementGuid>25da6ce8-a314-480b-9078-e285ec20da80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UnitPrice']</value>
      <webElementGuid>e05ccd2d-c8ed-4319-9be2-b6a23936d24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/span/span/input[2]</value>
      <webElementGuid>eba10b14-6eb7-48da-8f4f-26a4b9a7990d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'UnitPrice' and @name = 'UnitPrice' and @title = 'Unit Price']</value>
      <webElementGuid>71dbcdcf-e2f8-41c6-b799-280550d7ccb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
