<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Consumption_EnoughBenefits_Default_Co_454067</name>
   <tag></tag>
   <elementGuidId>520c54b6-6913-45ab-bfd2-ed5cdaeddc70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Consumption_EnoughBenefits_Y']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Consumption_EnoughBenefits_Y</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3700be41-75c5-42e4-bcf3-e93a152509f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-radio consumptionEnoughBenefits</value>
      <webElementGuid>9be266c9-9a2d-4d6c-8cdf-ec9bb014bc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e1afc39-35bb-4271-a2b3-46f49f39334f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Consumption_EnoughBenefits_Y</value>
      <webElementGuid>000c45ab-597c-4c00-ba71-76ead1a9c8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Consumption.EnoughBenefits</value>
      <webElementGuid>a909427b-7304-4d5b-9d01-8369167f91a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>enoughBenefits_change()</value>
      <webElementGuid>f918a1b7-e9fb-4664-8258-483aae6c41d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a8a01efe-4aff-49eb-9ec0-c74b7b08b07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>f2d43382-1223-4c5d-95cd-09ea71f109c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Consumption_EnoughBenefits_Y&quot;)</value>
      <webElementGuid>1609f946-a1ba-4795-9219-3c3d7236a7f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Consumption_EnoughBenefits_Y']</value>
      <webElementGuid>ea4f2839-82e1-4a91-9797-4a870b3e44b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='benefitsForm']/div/div/input[2]</value>
      <webElementGuid>6feb63f3-4512-487b-89e1-1f38bd253d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>9bc81ab4-4cf3-4064-9798-20012a043767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Consumption_EnoughBenefits_Y' and @name = 'Consumption.EnoughBenefits' and @type = 'radio']</value>
      <webElementGuid>e12a26a2-6f7c-41ff-8702-a9e94dfe46c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
