<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AccessPatientRecords_APRType_Default__6e28a2</name>
   <tag></tag>
   <elementGuidId>f8bc15b0-1b65-4a97-a1f6-ae813b285b4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccessPatientRecords_APRType_Patient']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AccessPatientRecords_APRType_Patient</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b95ec68-d272-49be-99f1-8c25d20875ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-radio AccessPatientRecordsAPRType</value>
      <webElementGuid>a276988a-8d59-4bc0-89cd-4756df02c096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eff119f0-5eea-4f64-9c87-c733a09ed60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccessPatientRecords_APRType_Patient</value>
      <webElementGuid>48d51f36-fcce-41d3-b4e2-d75af5130458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccessPatientRecords.APRType</value>
      <webElementGuid>d8911f51-f9cf-4250-8444-f1ff2ba1fcdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aprType_change()</value>
      <webElementGuid>042e32c3-52bf-441d-a5b0-f538166ad2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>026a1b2b-0fd5-433c-a929-5ef434060c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>364416c8-b02c-4fde-a3b2-5a4874f40403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccessPatientRecords_APRType_Patient&quot;)</value>
      <webElementGuid>0ed93d11-0158-41e0-8976-c4d499cb597b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccessPatientRecords_APRType_Patient']</value>
      <webElementGuid>2a0955ba-9776-4638-997b-c0a37e61f2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='consentValidation']/input[2]</value>
      <webElementGuid>9d62352b-7876-4f01-9d83-103ef72b1b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input[2]</value>
      <webElementGuid>033fbda6-956c-4d9c-884e-4cfb2734da5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccessPatientRecords_APRType_Patient' and @name = 'AccessPatientRecords.APRType' and @type = 'radio']</value>
      <webElementGuid>c6f9e008-71bc-4647-88bc-37d8dab04af7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
