<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accre Code_DoctorAccreCode</name>
   <tag></tag>
   <elementGuidId>daf3a3dd-e5f3-462e-bd29-a518f1b0f23a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='DoctorAccreCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;DoctorAccreCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>798ea92f-cb1b-4882-bbf8-04829e8305db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DoctorAccreCode</value>
      <webElementGuid>e03af000-b353-4f79-b71b-a5dfa1650192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-numeric maskedtextbox-dash k-textbox</value>
      <webElementGuid>54532885-8939-4170-9d2f-57aafbf76107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>maskedtextbox</value>
      <webElementGuid>470241ea-f9bd-4542-ad46-8cd520cd34b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>83a1f3a3-e45d-44bd-9be8-e605d3ad7fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value:DoctorAccreCode</value>
      <webElementGuid>29d09e30-695c-4e54-81e4-94f4d267c29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required-msg</name>
      <type>Main</type>
      <value>Doctor Accre Code field is required.</value>
      <webElementGuid>fb3d2b23-c9ef-412b-b4ce-b97ef0b6a210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;k-webkit k-webkit130 js&quot;]/body[@class=&quot;k-content&quot;]/div[@class=&quot;k-widget k-window&quot;]/div[@class=&quot;k-popup-edit-form k-window-content&quot;]/div[@class=&quot;k-edit-form-container&quot;]/div[@class=&quot;k-edit-field&quot;]/span[@class=&quot;k-widget k-maskedtextbox input-numeric maskedtextbox-dash&quot;]/input[@class=&quot;input-numeric maskedtextbox-dash k-textbox&quot;]</value>
      <webElementGuid>052fd59f-e0c0-421a-a220-fdde428a9d9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='DoctorAccreCode']</value>
      <webElementGuid>0e53edd5-6123-4fd0-bcca-6f8ccbc5b08b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/div/div[2]/span/input</value>
      <webElementGuid>5651b466-549b-48c3-a358-4cba7d6bccfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'DoctorAccreCode']</value>
      <webElementGuid>8c9d41c1-ea32-4f14-b4b2-463063d088f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
