<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date Signed_AccessPatientRecords.DateSigned</name>
   <tag></tag>
   <elementGuidId>6a242bbd-8e8f-4e35-9072-7cf57afad402</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccessPatientRecords_DateSigned']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AccessPatientRecords_DateSigned</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e443a29a-d2f1-4d35-a0c0-0d5f876b5557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-currentdate valid-date validate-ds date-signed k-input</value>
      <webElementGuid>f82f21b9-3733-4ae8-84b8-8cb03a80da39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>93bb5c6e-ecc2-4e4a-b43c-02446aeb6e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field Date Signed must be a date.</value>
      <webElementGuid>53f1d081-7699-407a-a6b4-b7a6e36a6004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccessPatientRecords_DateSigned</value>
      <webElementGuid>fb490e35-65f1-445d-9498-f6e4c0fab2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccessPatientRecords.DateSigned</value>
      <webElementGuid>836bffc4-8c93-4b8d-b464-778eebe71303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aebaa999-531c-4d16-b89f-31386b8b8927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>051b494e-e288-44ce-8d56-396b87c2e8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>a89e9e14-69b8-4916-acce-5774b81f6b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d52685c2-e363-4316-8f31-8ca28a49134f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>AccessPatientRecords_DateSigned_dateview</value>
      <webElementGuid>b1737a35-5d20-4c24-ac6b-663889c6f0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>16792f10-931b-43d4-891e-6dcb0d96aa33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>48f2603c-48d4-416c-b434-82a219c0cf7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>20b97c33-9e60-433d-8851-de3677624c65_cell_selected</value>
      <webElementGuid>f46fcfc6-7e76-4518-8317-fb1644816ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccessPatientRecords_DateSigned&quot;)</value>
      <webElementGuid>1761b531-a4b6-4af7-8b1a-e304d3a2a9ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccessPatientRecords_DateSigned']</value>
      <webElementGuid>f74fe681-ae49-4e09-8bfa-fff31795ff6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datesignedValidation']/span/span/input</value>
      <webElementGuid>56466c1d-4a2a-4ad9-ad85-b3493973a212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div/div/span/span/input</value>
      <webElementGuid>2e938c4e-0ea9-4c5c-a3e8-8222da861c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccessPatientRecords_DateSigned' and @name = 'AccessPatientRecords.DateSigned' and @type = 'text']</value>
      <webElementGuid>e6ccd1fc-a670-44ac-ba80-ec687bfffc2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
