<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Roles_k-multiselect-wrap k-floatwrap</name>
   <tag></tag>
   <elementGuidId>0d57aaae-15c7-4a5d-971a-2594cfccdc83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.k-multiselect-wrap.k-floatwrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='userInfoForm']/ul/li[6]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Add User&quot;i >> div >> internal:has-text=/^AdminUserDoctor$/ >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bc552f7e-5cca-4d09-bbc9-7f0f81f89e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-multiselect-wrap k-floatwrap</value>
      <webElementGuid>fd293c61-8b28-4f7d-a8c6-0c1047e504ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>7bfb64e3-4e5c-4e35-8e06-906d3d8c1c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>4690ac2e-3580-448b-bdbc-d0fa54385855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userInfoForm&quot;)/ul[@class=&quot;flex-list&quot;]/li[6]/div[@class=&quot;field-input&quot;]/div[@class=&quot;k-widget k-multiselect k-multiselect-clearable k-state-hover k-state-focused k-state-border-down&quot;]/div[@class=&quot;k-multiselect-wrap k-floatwrap&quot;]</value>
      <webElementGuid>3fa26cbd-d12e-403b-87d4-0d2024f5d37f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='userInfoForm']/ul/li[6]/div/div/div</value>
      <webElementGuid>b08e6a0f-d84a-4197-9010-70a58288035e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roles'])[2]/following::div[3]</value>
      <webElementGuid>506bdb94-bfb6-470e-9fd9-69dc4762aaa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[2]/following::div[4]</value>
      <webElementGuid>ba2704a9-938c-4c04-88a3-052eb7cf431b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELECT ONE'])[1]/preceding::div[3]</value>
      <webElementGuid>e0a587bc-fc8b-427e-ba53-361c8438a75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eurolink Network Intl Corp'])[2]/preceding::div[5]</value>
      <webElementGuid>800bc691-b137-4fed-9fce-a508f145a15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/div/div</value>
      <webElementGuid>d36a18ef-65c6-4807-ae0d-e46452e1a84d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
