<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Admin_flex-list-action</name>
   <tag></tag>
   <elementGuidId>29dc83ba-f79c-402b-b371-fff7e7703a8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(7) > div.flex-list-action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='userInfoForm']/ul/li[7]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Add User&quot;i >> div >> internal:has-text=&quot;Save&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>78049133-4f3b-46b1-af0a-22d188cbf361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-list-action</value>
      <webElementGuid>11ca6da1-a4a8-4810-87b7-cdfb04e04264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userInfoForm&quot;)/ul[@class=&quot;flex-list&quot;]/li[7]/div[@class=&quot;flex-list-action&quot;]</value>
      <webElementGuid>ca0830a1-fcd7-4a5c-b45d-b28665a4d78b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='userInfoForm']/ul/li[7]/div[2]</value>
      <webElementGuid>6d2d850d-9be9-4539-985c-93ba72a0e6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[13]/following::div[2]</value>
      <webElementGuid>2bf07073-2c83-49b9-8f32-b574356fc0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roles'])[2]/following::div[5]</value>
      <webElementGuid>1e7a220e-599f-491c-a67d-48433763a7d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELECT ONE'])[1]/preceding::div[1]</value>
      <webElementGuid>8a5fdfd1-ecaa-4e1c-8b4b-5d450b410d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eurolink Network Intl Corp'])[2]/preceding::div[3]</value>
      <webElementGuid>ab476f10-4240-4dad-bbb3-7c4fd87b4105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div[2]</value>
      <webElementGuid>0ddc679a-2816-4095-a6c6-b26f815e0f89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
