<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hospital Email_Hospital.HospitalEmail</name>
   <tag></tag>
   <elementGuidId>86a8e7b9-420c-4b41-950c-25f23a1216c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Hospital_HospitalEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Hospital_HospitalEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Hospital Email&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcc4d8bc-e015-4538-8f26-89baeb3eb3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-textbox k-textbox-md no-text-transform</value>
      <webElementGuid>cfd663f6-52e8-46ed-b956-8050b0322e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>145d8ca6-0218-4b95-8f62-d564e11a1f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-email</name>
      <type>Main</type>
      <value>The Hospital Email field is not a valid e-mail address.</value>
      <webElementGuid>cfe4eebf-d8b6-4d41-ae82-0e55475867c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Hospital Email field is required.</value>
      <webElementGuid>f8571591-dd8d-4629-81ed-7ebc52b8b6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Hospital_HospitalEmail</value>
      <webElementGuid>95a038f2-0f9b-44a2-abf9-83f9051b8348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Hospital.HospitalEmail</value>
      <webElementGuid>9b482727-b8e0-44e1-8cca-eaa5880c5527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>242d4350-9b8a-4e5d-891f-3dfc09241bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Hospital_HospitalEmail&quot;)</value>
      <webElementGuid>579f9e41-c2f2-4a06-8a29-752974432fff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Hospital_HospitalEmail']</value>
      <webElementGuid>191aad34-fbed-4823-bbb0-818d9b64ce38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hospitalInfoForm']/ul/li[4]/div/input</value>
      <webElementGuid>09b5b1c5-0695-4096-998b-95a9d8fab412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/ul/li[4]/div/input</value>
      <webElementGuid>94bd22c4-5321-42b6-a414-f1413a07fc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Hospital_HospitalEmail' and @name = 'Hospital.HospitalEmail' and @type = 'text']</value>
      <webElementGuid>3d1043f5-8664-4f6f-946a-cf805320698b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
