<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm password_Hospital.ConfirmPassword</name>
   <tag></tag>
   <elementGuidId>f30e3c09-57a9-4273-9a8e-c1df538e284e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Hospital_ConfirmPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Hospital_ConfirmPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Confirm password&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>855b5d7f-00b1-49da-9205-992a3237f7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-textbox k-textbox-md no-text-transform</value>
      <webElementGuid>d00eea9e-5b33-4873-926d-595ea314b643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>82b9d976-7a1a-4563-a7b9-c4291f25f9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto</name>
      <type>Main</type>
      <value>The Password and Confirmation Password do not match.</value>
      <webElementGuid>b57d07f8-2205-4675-ae90-c2ca236e70da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto-other</name>
      <type>Main</type>
      <value>*.Password</value>
      <webElementGuid>8dddf2aa-0f0e-4248-8766-306a5b10e528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Hospital_ConfirmPassword</value>
      <webElementGuid>c0515f12-ec15-41ca-b5ea-fa90cf880e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Hospital.ConfirmPassword</value>
      <webElementGuid>96489033-e1b8-498a-9027-696d7d2f0d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cf277626-1ab3-4f22-a6c4-bb1af740f177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Hospital_ConfirmPassword&quot;)</value>
      <webElementGuid>49f300a1-eca4-426b-87e0-4bc3f2ad69f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Hospital_ConfirmPassword']</value>
      <webElementGuid>249dd26a-a3b9-4595-a098-b1d6514a5308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hospitalInfoForm']/ul/li[8]/div/input</value>
      <webElementGuid>76eb066d-eb55-4861-864a-57eb73c44496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/input</value>
      <webElementGuid>061fccfa-05f3-4797-9f07-fc0bf335728f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Hospital_ConfirmPassword' and @name = 'Hospital.ConfirmPassword' and @type = 'password']</value>
      <webElementGuid>f3380fe6-2f34-4fdd-b3bf-88e1e77249db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
