<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Roles_k-input k-readonly</name>
   <tag></tag>
   <elementGuidId>ff1a6ad1-604b-4243-9367-527c70bcd352</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.k-input.k-readonly</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='userInfoForm']/ul/li[6]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=listbox[name=&quot;Roles*&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7920e14a-326e-4a43-ae59-6a53d4f15c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input k-readonly</value>
      <webElementGuid>0099625e-ee2b-4558-803e-bb7bb62a52a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3cccbe9f-da58-49d1-84f6-0640e06c8f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>699af237-f378-4c79-b47c-c7db20e97294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3e6ade08-60f9-4691-895a-38b46b0cd5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>529a062b-e9cc-4b17-b612-c35d47d4e7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>0d5ed25b-c54a-46da-9f49-b7990fa2282a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3b05bd86-cb3f-4e17-953b-410374f2736f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Roles_taglist</value>
      <webElementGuid>f5760441-8d2b-4fea-a6a7-1e493c47f5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>Roles_label</value>
      <webElementGuid>8e2ea42c-4573-477e-b44d-cd15423aab5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8b40abeb-6a55-4559-8520-0f35054d0307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-busy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5a561763-e889-4b84-a2f4-b0898b1af4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userInfoForm&quot;)/ul[@class=&quot;flex-list&quot;]/li[6]/div[@class=&quot;field-input&quot;]/div[@class=&quot;k-widget k-multiselect k-multiselect-clearable k-state-hover k-state-border-down&quot;]/div[@class=&quot;k-multiselect-wrap k-floatwrap&quot;]/input[@class=&quot;k-input k-readonly&quot;]</value>
      <webElementGuid>593dbaf0-4fcb-4148-9e2c-b08a92fd9ad8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='userInfoForm']/ul/li[6]/div/div/div/input</value>
      <webElementGuid>6a95d247-30c3-41c7-aba0-39096e13c553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>8cae9bf3-e2f1-4ef7-a29b-286c4665eaf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
