<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hospital Email_Hospital.HospitalEmail</name>
   <tag></tag>
   <elementGuidId>86a8e7b9-420c-4b41-950c-25f23a1216c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Hospital_HospitalEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Hospital_HospitalEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Hospital Email&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c44fdcaa-7d9d-4750-af45-9335a1201b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-textbox k-textbox-md no-text-transform</value>
      <webElementGuid>2740792b-adbc-4095-be03-056146f4dd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>faae6c5a-477e-4c3b-b5d1-9870c412ba57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-email</name>
      <type>Main</type>
      <value>The Hospital Email field is not a valid e-mail address.</value>
      <webElementGuid>12104d87-7103-4f27-ba55-a0b30ad0b7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Hospital Email field is required.</value>
      <webElementGuid>9679893a-8a81-4e87-b99f-af4119dbd1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Hospital_HospitalEmail</value>
      <webElementGuid>4d54a387-9859-4054-9386-e9faf3711b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Hospital.HospitalEmail</value>
      <webElementGuid>73096afb-2d63-4847-a9e5-09e8bb3edb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>402470af-a140-4a9a-ae08-23411b95f613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Hospital_HospitalEmail&quot;)</value>
      <webElementGuid>7d28afc8-2726-45c1-bc11-2995354f3c77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Hospital_HospitalEmail']</value>
      <webElementGuid>7ef31447-9a9e-4445-8be3-b433f69a96e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hospitalInfoForm']/ul/li[4]/div/input</value>
      <webElementGuid>0461f218-44df-4780-a845-31c681c691f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/ul/li[4]/div/input</value>
      <webElementGuid>48bd01ed-685b-4899-8535-586abe1bc3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Hospital_HospitalEmail' and @name = 'Hospital.HospitalEmail' and @type = 'text']</value>
      <webElementGuid>e6968928-6d9f-476d-bc6e-4bf9549c89c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
