<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_samplegmail.com_addUserBtn</name>
   <tag></tag>
   <elementGuidId>7b09373a-74d5-4eb0-addf-0a949c524337</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addUserBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addUserBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add User&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a31fd912-4ba2-45a4-a875-baebf7305e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addUserBtn</value>
      <webElementGuid>3cc754a8-4dbd-442e-829b-c674a99b1a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3265cad-9f93-446b-82b6-cac71c03de3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add User</value>
      <webElementGuid>9bd4d449-b5ee-4e80-8062-1c58d2f21b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-primary</value>
      <webElementGuid>4dd24bb6-b548-4cdb-9cd5-da6f2e61572c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addUser()</value>
      <webElementGuid>faaab92b-d459-44c1-a75f-e423e160e51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addUserBtn&quot;)</value>
      <webElementGuid>53256c54-6a16-4a9b-bbaf-94b1ffd77959</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addUserBtn']</value>
      <webElementGuid>f5599836-05fc-499f-ad7f-9f4f584c3091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='control-panel']/li[2]/div/p/input</value>
      <webElementGuid>c9d9d5cd-c9a5-4b91-a714-56933eaeeb04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>be107164-126c-4e19-83cc-da24b1cb9fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addUserBtn' and @type = 'button']</value>
      <webElementGuid>9f68291a-7ac1-46db-a0e5-a6ce89fa7ffe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
