<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm password_ConfirmPassword</name>
   <tag></tag>
   <elementGuidId>c8fac9aa-6336-4f97-b117-2206174638a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ConfirmPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ConfirmPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Confirm password&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44da620a-332a-4a16-93d0-89787112f6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-textbox no-text-transform</value>
      <webElementGuid>c9713067-dc44-4039-bd84-4725d91ba1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>76c8820e-79ad-4f44-9da8-366aaa35f5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto</name>
      <type>Main</type>
      <value>The Password and Confirmation Password do not match.</value>
      <webElementGuid>b817fd3f-fa2e-4b31-b7cb-fa8fc11d2074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto-other</name>
      <type>Main</type>
      <value>*.Password</value>
      <webElementGuid>64e3817a-dc9a-4827-8d6a-ed55a6492a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ConfirmPassword</value>
      <webElementGuid>b03271f2-374d-4333-bac4-24782ca1d5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ConfirmPassword</value>
      <webElementGuid>a9bc2a00-49b0-40f4-a06f-71b631f14e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7d1ef249-b953-4e50-b934-a313d461df33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ConfirmPassword&quot;)</value>
      <webElementGuid>4ddb1539-b893-4818-a7d8-9dbd9204fbab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ConfirmPassword']</value>
      <webElementGuid>539b8ab9-0fb4-464f-af63-659c3be7d051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='userInfoForm']/ul/li[4]/div/input</value>
      <webElementGuid>8649dfc3-6182-46bd-adc4-2514e8ccc3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/ul/li[4]/div/input</value>
      <webElementGuid>76939735-c070-43ce-a36f-2516686067a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ConfirmPassword' and @name = 'ConfirmPassword' and @type = 'password']</value>
      <webElementGuid>c61d8a40-b42c-456e-bbc1-106fc4a8610b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
