<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li</name>
   <tag></tag>
   <elementGuidId>0502fe81-bf71-4478-b7c3-ce8dd23bc092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(20)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='hospitalInfoForm']/ul/li[20]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Add Hospital&quot;i >> li >> internal:has-text=&quot;Save&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>01f6b811-9372-4ba7-90a5-300fe237e77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hospitalInfoForm&quot;)/ul[@class=&quot;flex-list&quot;]/li[20]</value>
      <webElementGuid>905888f4-0007-4ef0-aaf5-38c0447a0f28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hospitalInfoForm']/ul/li[20]</value>
      <webElementGuid>72013918-2609-4167-9d83-ebe392f79f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip Code'])[1]/following::li[1]</value>
      <webElementGuid>595e81b4-8f44-4099-b027-29c049909f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province'])[2]/following::li[2]</value>
      <webElementGuid>117f3361-9b3a-41e1-b36a-aa22c09036a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A. BELTRAN (CAMALIG)'])[1]/preceding::li[13]</value>
      <webElementGuid>11557a8b-0c82-4f6f-b347-53da74d130dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A. BONIFACIO'])[1]/preceding::li[14]</value>
      <webElementGuid>e511b377-d464-4765-9f5a-3f3886f09b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[20]</value>
      <webElementGuid>3e4cba78-1e39-4873-855a-6d19edc0f811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
