<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_1</name>
   <tag></tag>
   <elementGuidId>5d57daeb-6fba-4969-8359-2e7b79c441d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.flex-list > li:nth-of-type(7)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='userInfoForm']/ul/li[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Add User&quot;i >> li >> internal:has-text=&quot;Save&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>55f5a971-ed26-4e31-92d1-504c669a692c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userInfoForm&quot;)/ul[@class=&quot;flex-list&quot;]/li[7]</value>
      <webElementGuid>f21fd354-625d-4316-8658-b44154deacc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='userInfoForm']/ul/li[7]</value>
      <webElementGuid>a19d9d32-1694-4a52-91f8-00faaab16b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[13]/following::li[1]</value>
      <webElementGuid>14cecefd-0e5b-4368-b8df-871ca72b57f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roles'])[2]/following::li[2]</value>
      <webElementGuid>2e9cc552-8df5-45bf-8062-5941dad420cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELECT ONE'])[1]/preceding::li[1]</value>
      <webElementGuid>61b4b42d-3a27-4045-baf9-aba7ef90dd1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eurolink Network Intl Corp'])[2]/preceding::li[1]</value>
      <webElementGuid>05df279b-30c4-4b19-915f-4720e494ed1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/ul/li[7]</value>
      <webElementGuid>75a5a345-4035-4f91-b3ba-a33b08530267</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
