<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Admin_1</name>
   <tag></tag>
   <elementGuidId>ea9d4ea0-83a1-406e-8b9c-41deaf193e67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#2fb6d8e2-f7c1-4ddb-8a76-dd26e6f82a07</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='2fb6d8e2-f7c1-4ddb-8a76-dd26e6f82a07']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Admin&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5109a385-b9b4-400c-a3ef-eecfb74b259f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>45ff1aea-28e8-44b1-80f8-91e8d3c0bddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>856f3407-8540-4313-8277-523f941d08c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>0d7dd1f4-397d-4291-a2c5-659483f5196a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused k-state-hover</value>
      <webElementGuid>792e3715-eeaa-4a00-be4c-0f7bb0c41879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5580a8ca-4de0-40e1-a40e-da4a6947bec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5525844d-15b9-49e7-9473-63efbb8a4d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2fb6d8e2-f7c1-4ddb-8a76-dd26e6f82a07</value>
      <webElementGuid>8ce227c7-1130-4c83-adc1-6f5d2f3f7843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>009812a7-b762-47c0-9da1-15e9f28f163b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2fb6d8e2-f7c1-4ddb-8a76-dd26e6f82a07&quot;)</value>
      <webElementGuid>21a120e1-fd13-42cb-9e81-d39eb6093156</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='2fb6d8e2-f7c1-4ddb-8a76-dd26e6f82a07']</value>
      <webElementGuid>79dd3650-42d9-4750-a961-3a4ee6ab06b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Roles_listbox']/li</value>
      <webElementGuid>b7769e49-35dc-41ea-b2de-b7bb65f98c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[2]/following::li[1]</value>
      <webElementGuid>395dcb4d-c9af-422e-8444-5cb6a1c8a6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mapandan Community Hospital'])[2]/following::li[1]</value>
      <webElementGuid>ed5cc5fc-f530-4003-a18a-a8d07048b33d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[4]/preceding::li[1]</value>
      <webElementGuid>ea1baad8-415e-4f5d-aae0-6ebbaa178505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doctor'])[4]/preceding::li[2]</value>
      <webElementGuid>88718ff0-7410-4707-b2c5-8dffd531344d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li</value>
      <webElementGuid>e1c0d3cf-80d4-40de-89fe-0fa7e681d102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '2fb6d8e2-f7c1-4ddb-8a76-dd26e6f82a07' and (text() = 'Admin' or . = 'Admin')]</value>
      <webElementGuid>dbe13815-9f65-4a50-ac85-7f7929f90552</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
