<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_St. Peter Claver Hospital</name>
   <tag></tag>
   <elementGuidId>2d119bfa-0224-4892-8bd6-2a0fe9eb3bb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.k-item.k-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='HospitalInformationId_listbox']/li[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;St. Peter Claver Hospital&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a88e02d5-400f-4166-9a19-5f9c3b859540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>971d3bb7-5179-47db-9f6d-4e991fe5df19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>44ce5179-4c26-4099-8124-8ad28c761d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>caf02410-322e-410f-b4da-1e222513468e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-hover</value>
      <webElementGuid>f058edef-602a-46f7-9c2d-1373687008d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>882ab105-766e-4ada-a7f2-c47d4f0ffd10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>f4cdff1a-9ace-4448-98da-e351ef12fdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>St. Peter Claver Hospital</value>
      <webElementGuid>8f929f6b-a59b-4b2d-bb9f-fc3a8219524e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HospitalInformationId_listbox&quot;)/li[@class=&quot;k-item k-state-hover&quot;]</value>
      <webElementGuid>8d6c7098-a920-4c05-ad97-03cb26d6f0b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='HospitalInformationId_listbox']/li[7]</value>
      <webElementGuid>27921ec8-367c-41b8-92f8-d7268e758b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mapandan Community Hospital'])[2]/following::li[1]</value>
      <webElementGuid>ec8ecd99-a365-472b-a609-d48094eb7eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queensrow Central Maternity and Lying-In Clinic'])[2]/following::li[2]</value>
      <webElementGuid>b057155c-8e93-4cb7-a4c9-2613abfc94a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[2]/preceding::li[1]</value>
      <webElementGuid>44b60286-dc03-47ac-ba55-1dbcbe8969ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[8]/preceding::li[1]</value>
      <webElementGuid>2556507e-1546-448b-bbdf-8ae5716c3e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[7]</value>
      <webElementGuid>c5cfe7c9-1fc2-4ffe-a7d5-c16cf4bfc92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'St. Peter Claver Hospital' or . = 'St. Peter Claver Hospital')]</value>
      <webElementGuid>70d4bcff-5e87-4598-bf66-cf871e5e814a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
