<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_File Claim</name>
   <tag></tag>
   <elementGuidId>9a84a98e-0506-40c1-b0a1-b0c9087008eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addClaimBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addClaimBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;File Claim&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db328aa9-f528-4c65-b925-23d2ec4b4d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button</value>
      <webElementGuid>ae4e9d03-40c0-4ba0-b63f-453b46b2678a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Legacy_PrevBugv4/Claim/Create</value>
      <webElementGuid>691bb394-ba16-4a95-9aae-840373720d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addClaimBtn</value>
      <webElementGuid>36689353-e70a-4cf9-8f8a-72956342a4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>File Claim</value>
      <webElementGuid>ded68ba0-12af-4e39-b7b2-7ca0c26e63f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addClaimBtn&quot;)</value>
      <webElementGuid>8e61aab5-4c6e-4bd2-a2c4-969e83a9c873</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addClaimBtn']</value>
      <webElementGuid>3269be3e-00fe-4b48-b3d3-92a912a7dd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HomeTabStrip-1']/p/a</value>
      <webElementGuid>2ee6d65a-384f-4880-b624-65324c970f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'File Claim')]</value>
      <webElementGuid>e7d3202a-a835-4b22-90b2-4ade14ca22f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[129]/following::a[8]</value>
      <webElementGuid>7170e3a5-ee9b-4940-aeaf-8255e18730d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[128]/following::a[8]</value>
      <webElementGuid>0bbf8193-4525-4c74-af9c-184b1d880726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eurolink Network International Corporation'])[1]/preceding::a[1]</value>
      <webElementGuid>6c69ddfa-c360-4d41-a2de-59ad60c9f6e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/Legacy_PrevBugv4/Claim/Create')])[2]</value>
      <webElementGuid>728dbcc4-14e6-487c-b153-e4ce43850c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>4ccbf4ab-0d79-4626-858f-ab7f3df7e810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Legacy_PrevBugv4/Claim/Create' and @id = 'addClaimBtn' and (text() = 'File Claim' or . = 'File Claim')]</value>
      <webElementGuid>053c9b8f-00e2-4a50-bc59-615d4f730035</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
