<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_samplegmail.com_addUserBtn</name>
   <tag></tag>
   <elementGuidId>46d66d68-c29b-4239-a9c3-3b7fdbeb2dc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addUserBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addUserBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add User&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a0c9ef0-1515-46c4-963d-aae395f76a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addUserBtn</value>
      <webElementGuid>1d9baa09-d19a-4798-babb-da093b8ae252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>efc3fbf4-2974-41ab-813e-da5b8de6d9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add User</value>
      <webElementGuid>8936e5aa-a393-46a3-9349-e1d34f071fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-primary</value>
      <webElementGuid>cf77f855-e3fb-43c3-981f-4321526c0c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addUser()</value>
      <webElementGuid>7988fc29-5f53-4661-85eb-ed22384cf070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addUserBtn&quot;)</value>
      <webElementGuid>ec318348-6dbd-45c5-a549-a66f117511b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addUserBtn']</value>
      <webElementGuid>eede12d1-88ea-46de-9691-dcf18e05f5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='control-panel']/li[2]/div/p/input</value>
      <webElementGuid>11b53689-72dd-478a-9f71-8282539ec299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>60cbb284-4f6f-4282-8673-dadb5bf86f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addUserBtn' and @type = 'button']</value>
      <webElementGuid>8d499128-aaec-4148-9aa8-8edaac416bf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
