<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Check Eligibility</name>
   <tag></tag>
   <elementGuidId>3e50192a-075e-43d1-819f-a4aaf033615e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='checkEligibility']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.k-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de0facdd-84b4-4c63-89e6-dfa0d9f279c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>98b2b0f6-be76-4624-83f8-baa426618834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/OPSUI.EasyClaims.Legacy/Claim/Create?forEditing=True</value>
      <webElementGuid>d68e01cc-053c-4b13-8d52-2741aad8d790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>36723e55-08c5-4e96-8910-cdf5e694a35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check Eligibility</value>
      <webElementGuid>cdc9752a-c72e-411c-96a7-519d1c145d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkEligibility&quot;)/a[@class=&quot;k-link&quot;]</value>
      <webElementGuid>981dd0b0-b6df-4ca6-a544-a2848cddeaf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='checkEligibility']/a</value>
      <webElementGuid>603084fb-7bc2-4b61-88a7-34890a33d948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Check Eligibility')]</value>
      <webElementGuid>e970821b-3b61-4039-939a-87d560c50848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Control Panel'])[1]/following::a[1]</value>
      <webElementGuid>d0d77f83-ecb4-4d5f-bf16-f0ff1391951b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log off'])[1]/following::a[2]</value>
      <webElementGuid>55745480-dad6-4520-a9e7-e4961151d44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confinement Information'])[1]/preceding::a[1]</value>
      <webElementGuid>c27e9eb6-5993-402b-8fba-c4ad3c6e0e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fees and Charges'])[1]/preceding::a[2]</value>
      <webElementGuid>82ecd45e-b7d0-4fc3-b39c-6eef1399ab2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Check Eligibility']/parent::*</value>
      <webElementGuid>04403d1e-0ea1-471f-90b1-43a464325134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/OPSUI.EasyClaims.Legacy/Claim/Create?forEditing=True')]</value>
      <webElementGuid>af25b0fb-6c34-45c6-a735-3d58d927dc73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>e341e489-bcbb-4a70-9c2e-1277099ecb62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/OPSUI.EasyClaims.Legacy/Claim/Create?forEditing=True' and (text() = 'Check Eligibility' or . = 'Check Eligibility')]</value>
      <webElementGuid>0210f181-ede8-4383-aefe-93d34217269a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
