<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nov 01, 2024_detail s0-</name>
   <tag></tag>
   <elementGuidId>5e00f53f-3a39-48dc-978e-3ad562786ecd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.detail.s0-</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.detail</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4929dc4f-9945-4b9e-8c4b-10290ae8f2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>detail s0-</value>
      <webElementGuid>2278b811-04c4-4465-bfa8-6b93dcf83249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>detail_1</value>
      <webElementGuid>f6730b00-a2c6-4306-9c5e-89bc160178d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;print-page&quot;]/div[@class=&quot;sheet page1&quot;]/div[@class=&quot;layer&quot;]/div[@class=&quot;detail s0-&quot;]</value>
      <webElementGuid>85b6c225-2b37-46a1-ac4e-c1f878ea9b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ECMSprint3/ECM_BillingStatement/Page_Billing Statement Report - Easy Claims_285efc/iframe_Generating report_ReportsViewerReportFrame</value>
      <webElementGuid>85038642-d992-4958-89d6-003987b4a67e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]</value>
      <webElementGuid>5e64254f-1275-463f-82bb-7513cba564b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
