<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_This page requires frames in order t_99ba60_1</name>
   <tag></tag>
   <elementGuidId>21f1e05b-2964-4dde-9cc6-50d636b946ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.k-content-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='0ee04b43-3a8e-4ad1-855f-2550d4c2870c']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Billing Statement&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ccfa026a-737e-4894-95b2-b16dc77ce2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5ad656e0-a5da-4a5b-91e0-da0dc8289052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Billing Statement</value>
      <webElementGuid>87c256e6-0507-4ad0-a0f2-8faf93199cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-content-frame</value>
      <webElementGuid>53752c4d-aac8-4698-b7a3-b59b34992fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ECManager_Sprint3/Reporting/Reports.aspx?filters={&quot;ReportType&quot;:&quot;BillingStatement&quot;,&quot;Id&quot;:88518,&quot;AccountId&quot;:631}</value>
      <webElementGuid>1063f603-fc00-4349-9ae7-75dd97a3b2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This page requires frames in order to show content</value>
      <webElementGuid>98b3e997-d05d-46fc-97ff-8509df3a29f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0ee04b43-3a8e-4ad1-855f-2550d4c2870c&quot;)/iframe[@class=&quot;k-content-frame&quot;]</value>
      <webElementGuid>95bcd91e-02b5-464e-9f34-59844f904ba2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0ee04b43-3a8e-4ad1-855f-2550d4c2870c']/iframe</value>
      <webElementGuid>2c5712b7-ed33-42a0-b09c-a4dcef450049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Statement'])[4]/following::iframe[1]</value>
      <webElementGuid>50aa266d-244a-4adc-ab79-7e857b458713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[4]/following::iframe[1]</value>
      <webElementGuid>4dc38f5e-92b9-4d97-9d3b-67006a1ad95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This page requires frames in order to show content']/parent::*</value>
      <webElementGuid>3b569873-3548-492e-baa5-d04f40e7ae7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>77a08fea-2118-4c78-b3de-f6caf704ab1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Billing Statement' and @src = '/ECManager_Sprint3/Reporting/Reports.aspx?filters={&quot;ReportType&quot;:&quot;BillingStatement&quot;,&quot;Id&quot;:88518,&quot;AccountId&quot;:631}' and (text() = 'This page requires frames in order to show content' or . = 'This page requires frames in order to show content')]</value>
      <webElementGuid>f2a1b181-37df-4422-b808-67993b540256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
