<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Generating report_ReportsViewerReportFrame</name>
   <tag></tag>
   <elementGuidId>91bc9ec1-890f-4ca8-9169-e6b162ffc0e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReportsViewerReportFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ReportsViewerReportFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ReportsViewerReportFrame</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>dae4af70-48b3-44c0-ad07-af1de596c1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReportsViewerReportFrame</value>
      <webElementGuid>0757b9be-b85e-4b74-9b06-4926eb55de96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>68fda47f-39b4-4927-a0c9-f6d0d644cc0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>dbcebc59-710f-4765-b835-957a7f2af199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>2ae3030f-61fd-487a-9cee-875a8e832e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ECManager_Sprint3/Telerik.ReportViewer.axd?instanceID=c552882b84894309b65cc87761864a2b&amp;optype=Report&amp;PageIndex=0&amp;RenderID=289029c7b4b84850805cbf439fcccf41&amp;RenderingFormat=HTML5</value>
      <webElementGuid>d4bbcdbf-3737-4ba7-bfc3-85b0c59a81dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReportsViewerReportFrame&quot;)</value>
      <webElementGuid>7e9c4da0-d078-4ccc-ba1c-3cab2b40a059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ECMSprint3/ECM_BillingStatement/Page_Billing Statement Report - Easy Claims_285efc/iframe_This page requires frames in order t_99ba60</value>
      <webElementGuid>7fbe3de6-ac9c-491e-ad72-25d5399783a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ReportsViewerReportFrame']</value>
      <webElementGuid>14b24304-1982-49ba-9d20-29593a9e7c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ReportsViewer_ReportArea_ReportCell']/iframe</value>
      <webElementGuid>536a4e7b-b0c0-4b08-a570-d9fc626747e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/iframe</value>
      <webElementGuid>e1f97a60-4c7c-45d8-80c4-4860152d9365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ReportsViewerReportFrame' and @src = '/ECManager_Sprint3/Telerik.ReportViewer.axd?instanceID=c552882b84894309b65cc87761864a2b&amp;optype=Report&amp;PageIndex=0&amp;RenderID=289029c7b4b84850805cbf439fcccf41&amp;RenderingFormat=HTML5']</value>
      <webElementGuid>7f90bed2-c66d-4f43-8160-1aab33ce57cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
