<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_This page requires frames in order t_99ba60</name>
   <tag></tag>
   <elementGuidId>7a877bbb-f700-4f52-9bf5-2cc177c84da6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.k-content-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c17eff60-a96b-4ea5-97b2-2c78fc5df78c']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Billing Statement&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4f3701d6-d1ba-4b03-abc7-607b36cfadba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e47f5a87-a241-423d-a981-873a25ea25ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Billing Statement</value>
      <webElementGuid>95fbefd5-ea90-481d-8e9e-6b8a328cf9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-content-frame</value>
      <webElementGuid>ae751d04-9986-4dfb-96e8-7532b75a3257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ECManager_Sprint3/Reporting/Reports.aspx?filters={&quot;ReportType&quot;:&quot;BillingStatement&quot;,&quot;Id&quot;:90399,&quot;AccountId&quot;:1}</value>
      <webElementGuid>8f362aed-bd40-48b4-856f-9e4f800c9216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This page requires frames in order to show content</value>
      <webElementGuid>5fc95358-69c4-4750-8db5-28f5291c133f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c17eff60-a96b-4ea5-97b2-2c78fc5df78c&quot;)/iframe[@class=&quot;k-content-frame&quot;]</value>
      <webElementGuid>857e9664-9761-496e-a974-4ce3c7a8b2c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c17eff60-a96b-4ea5-97b2-2c78fc5df78c']/iframe</value>
      <webElementGuid>40e1736e-5fb5-4848-8a1b-561becf42f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Statement'])[4]/following::iframe[1]</value>
      <webElementGuid>559c50cb-97a9-4172-80a3-da7565caf1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[3]/following::iframe[1]</value>
      <webElementGuid>c700000a-5a92-477d-8dfd-7d7d58cb0ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This page requires frames in order to show content']/parent::*</value>
      <webElementGuid>2b35e587-cbb1-4cf5-8481-54cf5bdb26dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>335c5650-95b1-4093-b3c5-bb372dc53cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Billing Statement' and @src = '/ECManager_Sprint3/Reporting/Reports.aspx?filters={&quot;ReportType&quot;:&quot;BillingStatement&quot;,&quot;Id&quot;:90399,&quot;AccountId&quot;:1}' and (text() = 'This page requires frames in order to show content' or . = 'This page requires frames in order to show content')]</value>
      <webElementGuid>5192ada7-e668-4525-8d56-dc0e768f5b40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
