<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Generating report_ReportsViewerReportFrame (1)</name>
   <tag></tag>
   <elementGuidId>041ac3cd-61d9-481c-835e-000f0a4f32fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReportsViewerReportFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ReportsViewerReportFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ReportsViewerReportFrame</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>072c24be-0acf-4c6e-a238-a93c46e12fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReportsViewerReportFrame</value>
      <webElementGuid>b4a41b04-91e5-4278-96fd-14b70d1d7d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8cd66511-5ad1-4ccf-ade3-6054e3a534f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>8f893e4c-5a0e-4083-add0-839b0e8a1489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>9b1b7f1f-113e-4345-a658-d40e70100497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ECManager_Sprint3/Telerik.ReportViewer.axd?instanceID=a56f80147b7f4619980f7689bb7459bb&amp;optype=Report&amp;PageIndex=0&amp;RenderID=57001a0067614cb7a68f97d1ccb102aa&amp;RenderingFormat=HTML5</value>
      <webElementGuid>77f5ea34-9e72-49f3-b758-d4079e2af69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReportsViewerReportFrame&quot;)</value>
      <webElementGuid>ca517e1c-0d0d-46c9-9a22-5aae905ea73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ECMSprint3/ECM_BillingStatement/Page_Billing Statement Report - Easy Claims_285efc/iframe_This page requires frames in order t_99ba60_1</value>
      <webElementGuid>d2499411-599f-44ea-a6d9-e4f73968a6e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ReportsViewerReportFrame']</value>
      <webElementGuid>5f5596ca-99b7-4305-8c6e-4bd6e8dbc791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ReportsViewer_ReportArea_ReportCell']/iframe</value>
      <webElementGuid>75d04dda-d488-447c-8629-ed6339261236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/iframe</value>
      <webElementGuid>86d64555-ea8d-486d-aa91-0c8538c782e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ReportsViewerReportFrame' and @src = '/ECManager_Sprint3/Telerik.ReportViewer.axd?instanceID=a56f80147b7f4619980f7689bb7459bb&amp;optype=Report&amp;PageIndex=0&amp;RenderID=57001a0067614cb7a68f97d1ccb102aa&amp;RenderingFormat=HTML5']</value>
      <webElementGuid>dfee0c39-a169-47ed-8574-f96b84198469</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
