<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Equals_k-textbox</name>
   <tag></tag>
   <elementGuidId>284d1440-6369-4336-8e35-b8b038505648</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.k-textbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Value&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a9dd9de-c5c1-46dc-bd99-a2a4918d4f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Value</value>
      <webElementGuid>95f4405a-a619-4927-85de-e5ea452add0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value:filters[0].value</value>
      <webElementGuid>307f9533-bc53-47a0-9429-0bc7535419ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-textbox</value>
      <webElementGuid>3bc5c767-7094-4cd3-bc97-6754f3afccf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5cd7ad3f-9726-4631-b235-e6fd7b665a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ada1d89d-1ed8-4988-b9b5-fc578acbedad_mn_active&quot;)/div[@class=&quot;k-animation-container&quot;]/ul[@class=&quot;k-group k-menu-group k-popup k-reset k-state-border-left&quot;]/li[@class=&quot;k-item k-menu-item k-state-default k-first k-last&quot;]/div[@class=&quot;k-filterable k-content&quot;]/form[@class=&quot;k-filter-menu&quot;]/div[@class=&quot;k-filter-menu-container&quot;]/input[@class=&quot;k-textbox&quot;]</value>
      <webElementGuid>91134f48-2e60-4931-a3e0-945f05382b71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>045b2c63-6cb5-4ce8-bb69-7bccb4dc965a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ada1d89d-1ed8-4988-b9b5-fc578acbedad_mn_active']/div/ul/li/div/form/div/input</value>
      <webElementGuid>aa38f32e-697a-4de8-b38f-20a9cf9cef29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>67aa9da6-97bb-452f-a57f-9b38f602edc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Value' and @type = 'text']</value>
      <webElementGuid>4fde94c2-6428-4c72-94bd-87ceae273239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
