<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Filter</name>
   <tag></tag>
   <elementGuidId>7a1822da-0972-4364-8dec-1eec46d3b259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-link.k-menu-link.k-state-active.k-state-border-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[2]/following::span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=&quot;Filter&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>58f59f2d-26c8-4b6c-8ddd-f1ff15e0ad03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link k-menu-link k-state-active k-state-border-right</value>
      <webElementGuid>4f3e1941-01c4-4891-b955-a376c8d214f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter</value>
      <webElementGuid>e00f4283-ccfb-45b2-9177-7e9f08b273ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ada1d89d-1ed8-4988-b9b5-fc578acbedad&quot;)/li[@class=&quot;k-item k-menu-item k-filter-item k-state-default k-last k-state-hover k-state-border-right&quot;]/span[@class=&quot;k-link k-menu-link k-state-active k-state-border-right&quot;]</value>
      <webElementGuid>3d1459f8-eb64-4e4b-aea6-2d00459cfc8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ada1d89d-1ed8-4988-b9b5-fc578acbedad']/li[6]/span</value>
      <webElementGuid>ce6376ea-cc16-4a9d-8357-7a50e6e6beb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[2]/following::span[2]</value>
      <webElementGuid>48828ec4-52dc-4be3-9bdc-aab3a1999f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Issued'])[2]/following::span[3]</value>
      <webElementGuid>1bcf00a2-5ecf-4d23-8ac1-a32d0f974b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show items with value that:'])[1]/preceding::span[3]</value>
      <webElementGuid>632ee3a8-c174-4284-99ca-533c01a9c418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equals'])[1]/preceding::span[3]</value>
      <webElementGuid>9df418ea-5d1e-42a8-afb0-a128240a2541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Filter']/parent::*</value>
      <webElementGuid>f3ee0813-fa72-47f9-9d93-1feb332e0687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/span</value>
      <webElementGuid>3f2bdb9f-547a-4825-9fc1-89380ff00ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Filter' or . = 'Filter')]</value>
      <webElementGuid>8c4b74d2-9370-4a61-9594-f45e5a93bd70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
