<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_00004_1</name>
   <tag></tag>
   <elementGuidId>92d9df8c-5b5b-4d94-8b5e-7080d8e079fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.k-virtual-item.k-item.k-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='UnitCode_listbox']/li[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;00004&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>03e4eee1-3c69-45df-b169-36293563ce97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9bdbcfa7-e6b2-4926-937b-3248e29a4b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-virtual-item k-item k-state-hover</value>
      <webElementGuid>7866debc-7b50-48e6-9992-adb9965e3794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>65704562-eb40-4cee-8e5d-7fbfb371d957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uid</name>
      <type>Main</type>
      <value>533f7363-2b7c-4f3a-8e8f-ff5fdcd73815</value>
      <webElementGuid>709f735c-9937-4ccc-b2f0-2021bc503551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>af7c3308-c250-4e05-a0a4-b0258ad8f16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>00004</value>
      <webElementGuid>19daf52c-e66e-491e-bc94-d2b869c1c1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UnitCode_listbox&quot;)/li[@class=&quot;k-virtual-item k-item k-state-hover&quot;]</value>
      <webElementGuid>7f5e1daa-c788-483e-9dc5-c6cca5629d07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='UnitCode_listbox']/li[5]</value>
      <webElementGuid>1da9dd22-bbd8-4d78-b1fe-9bf7fa29cde3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select one'])[7]/following::li[5]</value>
      <webElementGuid>f1dfbcd3-0a3f-44d8-be9b-a3bcafffd702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[4]/following::li[5]</value>
      <webElementGuid>f77d9f7b-28e0-4b6b-b7f9-99b5d0f7e39e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[5]/preceding::li[27]</value>
      <webElementGuid>33fb485e-d673-4dcb-b7e7-d2f68908b87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select one'])[8]/preceding::li[27]</value>
      <webElementGuid>ddbed538-bb6e-4001-b546-659a4a2e7846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[23]/div/div[2]/div[2]/ul/li[5]</value>
      <webElementGuid>bbc1442b-aacc-455e-9df6-d849e5868866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '00004' or . = '00004')]</value>
      <webElementGuid>ce980677-795c-4972-8c68-81fca29f55c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
