<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_100PC</name>
   <tag></tag>
   <elementGuidId>005f9605-03c3-4e13-976f-06a85c45bb95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.k-virtual-item.k-item.k-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='PackageCode_listbox']/li[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;100PC&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1696a1a7-7799-489c-b828-3f98844f771e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>839b9a4a-a701-472e-8a07-3982bb61d647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-virtual-item k-item k-state-hover</value>
      <webElementGuid>2cc9cbde-5d07-4f21-a66b-8460d4db6c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9d134f46-905d-4075-8ab3-37dbf920340c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uid</name>
      <type>Main</type>
      <value>6624a413-e3e7-4fbc-95d4-3b256ad6fb7a</value>
      <webElementGuid>4bfea313-6682-48bb-99ca-bfdd88f84fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9b5a1aeb-3029-432d-9fc6-d37da42bb579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100PC</value>
      <webElementGuid>2deb73db-4677-4044-a0c8-b722ea5b58a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PackageCode_listbox&quot;)/li[@class=&quot;k-virtual-item k-item k-state-hover&quot;]</value>
      <webElementGuid>4b57fca6-f972-4381-9505-79d2cf47e745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='PackageCode_listbox']/li[4]</value>
      <webElementGuid>a6f2fc73-9f34-445e-b698-9d2a114177d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select one'])[7]/following::li[4]</value>
      <webElementGuid>ee22d345-4366-4992-ae44-13b8425e21eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[5]/following::li[4]</value>
      <webElementGuid>6f07992a-76bc-45e5-9c01-54a10f2fa496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[6]/preceding::li[28]</value>
      <webElementGuid>261c9bc1-0247-4af5-bcb8-7329f74aeba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Getting unit code information succeed.'])[1]/preceding::li[28]</value>
      <webElementGuid>233fc1a0-a17a-4189-8bab-868ad969bc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='100PC']/parent::*</value>
      <webElementGuid>b2f572ca-cd5a-4fd9-8d06-e2fefa4934fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/div/div[2]/div[2]/ul/li[4]</value>
      <webElementGuid>20fb0de7-2506-45e6-b0f1-447a89555c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '100PC' or . = '100PC')]</value>
      <webElementGuid>93cfab20-6883-4518-9932-86796d148516</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
