<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_AEROS</name>
   <tag></tag>
   <elementGuidId>e923a043-29ee-4393-8dff-2016505d7c9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.k-virtual-item.k-item.k-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='FormCode_listbox']/li[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;AEROS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>00aa04e4-a6d2-42b5-a637-0fe612824c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6b65d2f8-b86c-423e-8480-0c8556550d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-virtual-item k-item k-state-hover</value>
      <webElementGuid>e0c6abd6-d320-4c86-b3c4-43204c1d43bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>fa0f832c-c005-417a-ab6d-f679b0297927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uid</name>
      <type>Main</type>
      <value>32c81b87-1e98-4c84-98ae-f11a12ec89d5</value>
      <webElementGuid>0665fefd-c77b-4cc9-a521-829038f31e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>75e7c4e8-5c55-4e85-83aa-4588176edd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AEROS</value>
      <webElementGuid>da66413c-0bf9-4b60-b3cb-cb52adae05a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormCode_listbox&quot;)/li[@class=&quot;k-virtual-item k-item k-state-hover&quot;]</value>
      <webElementGuid>cfa004ec-5bf3-46ed-a4af-e1ac8852b30b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='FormCode_listbox']/li[5]</value>
      <webElementGuid>9abe5f34-f6ee-4970-bca4-fb4e01dc1470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AERO3'])[1]/following::li[1]</value>
      <webElementGuid>621109e6-0491-494f-90ed-df3e62899e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AERO2'])[1]/following::li[2]</value>
      <webElementGuid>e1026f91-ff86-4835-902d-5e1b6aace00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAM01'])[1]/preceding::li[1]</value>
      <webElementGuid>f381b11c-ba8d-444e-be02-6a179ef77764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BARCH'])[1]/preceding::li[2]</value>
      <webElementGuid>b28f4f61-9837-456b-8e32-378868a4ae2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AEROS']/parent::*</value>
      <webElementGuid>3835d959-cb10-4e7f-9de6-d6440f1f7c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div[2]/div[2]/ul/li[5]</value>
      <webElementGuid>e1a054f2-63a8-482a-8140-3c281eef0eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'AEROS' or . = 'AEROS')]</value>
      <webElementGuid>9993e5c7-613c-4c8c-9501-51d83345445c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
