<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_File Claim</name>
   <tag></tag>
   <elementGuidId>1abc7a62-3469-4e8b-9fda-e3eea694b60a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addClaimBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addClaimBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;File Claim&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ee22949-aefa-49e5-8938-ce3086367423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button</value>
      <webElementGuid>2df29778-fdd3-415f-b1ae-a3d3eda15273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Legacy_PrevBugv4/Claim/Create</value>
      <webElementGuid>a7180a5b-7f3d-4f5c-be9d-939dc9eadd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addClaimBtn</value>
      <webElementGuid>72a9ac51-b328-43d7-ae99-db1715cf54ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>File Claim</value>
      <webElementGuid>7309c210-0544-4a09-bae1-d2848e36b392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addClaimBtn&quot;)</value>
      <webElementGuid>51c30852-bac2-4191-8e8e-7669956f8663</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addClaimBtn']</value>
      <webElementGuid>ccc137aa-8778-4597-9f6f-0b9a4ef2d951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'File Claim')]</value>
      <webElementGuid>09a2d323-a786-4acf-a57d-6c2f890c6bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='patcheadmin2'])[4]/following::a[12]</value>
      <webElementGuid>322a26bc-fe14-4f4f-86a8-ad3b96281bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='patcheadmin2'])[3]/following::a[12]</value>
      <webElementGuid>126a2eb3-12e5-4da9-9629-e3634c1c5c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eurolink Network International Corporation'])[1]/preceding::a[1]</value>
      <webElementGuid>09aae810-3a46-4419-9dc7-bdd33f62adbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/Legacy_PrevBugv4/Claim/Create')])[2]</value>
      <webElementGuid>97c92a43-bf27-4648-813c-7f857629191e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>e53f1e2e-2041-4d65-8bf2-d184a9036b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Legacy_PrevBugv4/Claim/Create' and @id = 'addClaimBtn' and (text() = 'File Claim' or . = 'File Claim')]</value>
      <webElementGuid>e8cd7dc6-d74b-4f44-bf92-8e018759f510</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
