<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Generating and printing of this form _08f184</name>
   <tag></tag>
   <elementGuidId>458ce4e1-4363-4ba1-a17a-1af509851150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exportPDFBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p/input[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Export as PDF&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26d24ac3-991c-4731-afe6-ae699c0dbd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exportPDFBtn</value>
      <webElementGuid>623f0eb6-7737-4fc1-8fb5-f03697583c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d308666-0d35-4da9-8b44-5aadc3a196ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-secondary</value>
      <webElementGuid>c21f3b5f-af5d-46e2-b340-5b7e58667b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Export as PDF</value>
      <webElementGuid>a20fccd7-00f7-4d43-876a-c06d779def08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>exportPBEF()</value>
      <webElementGuid>a31d2c2d-7cf0-4d4e-b595-cab73fd12251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exportPDFBtn&quot;)</value>
      <webElementGuid>f517f750-9e3c-440d-bfc0-a7fb96dcaaff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exportPDFBtn']</value>
      <webElementGuid>958bb6fc-510d-45c3-aa3c-101bd6c9246e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input[2]</value>
      <webElementGuid>e404efc4-0c86-4d2d-b997-be03c67a6c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'exportPDFBtn' and @type = 'button']</value>
      <webElementGuid>19b3ef64-d6b9-41de-8951-f616ad88aaf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
