<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Is equal to</name>
   <tag></tag>
   <elementGuidId>07953890-da07-42dc-a6af-6edfedc6931c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#89a3b685-2be5-41c2-b0ca-6a8173572e3d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='89a3b685-2be5-41c2-b0ca-6a8173572e3d']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Is equal to&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5245fd96-c572-463e-b764-f478a6c71ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>cb1df743-674b-4a51-88bb-e238da8cc64d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>243a9753-7ce4-4ec8-aa4d-1b62656a82d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>cb74ca8e-5d10-4ce8-a82b-c45cbfeb163c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-selected k-state-focused k-state-hover</value>
      <webElementGuid>29b029b3-10d1-4f99-a359-67ddba412eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4bb4d093-0317-4954-be44-18e18c459beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ad7a796a-0e3c-4d04-8897-17989e49df6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>89a3b685-2be5-41c2-b0ca-6a8173572e3d</value>
      <webElementGuid>9886c39b-3677-4d76-99b6-353c4aa91ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Is equal to</value>
      <webElementGuid>5ebec323-6fc2-4006-806b-f266907de3b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;89a3b685-2be5-41c2-b0ca-6a8173572e3d&quot;)</value>
      <webElementGuid>1e01e5f8-c965-460b-a0c8-3f095b50ee21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='89a3b685-2be5-41c2-b0ca-6a8173572e3d']</value>
      <webElementGuid>37db7a0b-33e9-48e1-b841-0a0b6c0b0132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='34032345-d7e5-44a3-9502-ac9f1af82b00_listbox']/li</value>
      <webElementGuid>1cfebcc2-4974-4a3a-b914-42b0072b14c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::li[1]</value>
      <webElementGuid>ad10fb0c-a59a-4e91-bd81-b496247332de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[2]/following::li[1]</value>
      <webElementGuid>27858847-20d6-475f-b57b-3cb39052b0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is not equal to'])[3]/preceding::li[1]</value>
      <webElementGuid>88c31c27-8e13-454b-81e3-66a19c85d63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Starts with'])[3]/preceding::li[2]</value>
      <webElementGuid>41327b92-ef1f-464f-97c4-560031e1b084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li</value>
      <webElementGuid>54345fc5-d039-4abc-a40a-ffdbd3aa68df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '89a3b685-2be5-41c2-b0ca-6a8173572e3d' and (text() = 'Is equal to' or . = 'Is equal to')]</value>
      <webElementGuid>8efb9e1c-3cd5-4a23-a0ce-3931d1a67fef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
