<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_This page requires frames in order t_99ba60</name>
   <tag></tag>
   <elementGuidId>096c7342-1a06-42b0-a6a4-017c33c3a428</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.k-content-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b0a50a88-788c-46db-b0dd-c3ccaaae248e']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Generate AR Letter&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>dcf85fd1-1449-435f-b7b9-b55570511acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>470a387c-b88f-409e-93c4-e028996de4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Generate AR Letter</value>
      <webElementGuid>d4364e9e-e12f-4f15-8606-c9e1f4708b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-content-frame</value>
      <webElementGuid>67e5829a-7ce0-43f2-a758-f5068ba2774f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ECManager_Sprint3/AR/GenerateAR</value>
      <webElementGuid>e2969a0a-4eac-4c7f-a9f2-e5e07f0edb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This page requires frames in order to show content</value>
      <webElementGuid>251c894d-76fa-4f6f-853a-765b026b9fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b0a50a88-788c-46db-b0dd-c3ccaaae248e&quot;)/iframe[@class=&quot;k-content-frame&quot;]</value>
      <webElementGuid>010a56b5-40d7-4198-b41b-66a302cc975b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b0a50a88-788c-46db-b0dd-c3ccaaae248e']/iframe</value>
      <webElementGuid>dcfc8e96-8d8f-4aa5-89f5-66635e583e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate AR Letter'])[1]/following::iframe[1]</value>
      <webElementGuid>be5793dd-4069-4246-848c-207107bc2782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statement Of Account'])[2]/following::iframe[1]</value>
      <webElementGuid>1c5797b6-2193-4834-9fea-a7eaa0e403e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This page requires frames in order to show content']/parent::*</value>
      <webElementGuid>522409de-faf3-4d49-b666-6e0484cc19d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>28b3ba4f-47ff-4a58-92c1-b9fecad926d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Generate AR Letter' and @src = '/ECManager_Sprint3/AR/GenerateAR' and (text() = 'This page requires frames in order to show content' or . = 'This page requires frames in order to show content')]</value>
      <webElementGuid>76b1a5a9-b8ae-446f-a23c-5ad8e2ac9df9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
