<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Selected Account Receivables_SearchTerm</name>
   <tag></tag>
   <elementGuidId>a3a47de7-1655-4c96-8f41-8d9b400e3e25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SearchTerm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SearchTerm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18f849b8-9cc8-4e20-b87c-4b27fcdeaa6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SearchTerm</value>
      <webElementGuid>c4797d8d-59cd-4770-9ecc-938bbad47169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1e19e616-0d66-4b4e-935d-3052e18abe4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchTerm</value>
      <webElementGuid>ca0baab0-29a0-44a2-ba75-5a0108f3be19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>7c0419ce-b6e5-4d8b-afd3-64a61ee658c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-textbox k-textbox-lg search-filter</value>
      <webElementGuid>53fd4e0f-d060-4b59-be53-e766dcf1188e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0d0ca160-d14a-4e4d-9ac9-cfcec4eff33a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchTerm&quot;)</value>
      <webElementGuid>6ae69a73-45b7-439a-90d4-db02fe9bdacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ECMSprint3/ECM_AR/Page_Account Receivable - Easy Claims Manager/iframe_This page requires frames in order t_99ba60</value>
      <webElementGuid>d4325b18-3926-414c-bd54-6074a2e4e9ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SearchTerm']</value>
      <webElementGuid>df1e8c4f-3e88-4362-8c2f-c3c37a337d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>32237769-5981-4c1d-8682-ee988c83dac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SearchTerm' and @type = 'text' and @name = 'SearchTerm' and @placeholder = 'Search']</value>
      <webElementGuid>afee47fb-a008-46f9-b1bf-e20f12ac00d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
