<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Selected Account Receivables_ProcessButton</name>
   <tag></tag>
   <elementGuidId>62c1e3c8-5bc6-4502-a04f-57fa6a8128bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProcessButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProcessButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28ec0172-7f30-4202-bfbc-cc11a74ebad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProcessButton</value>
      <webElementGuid>190c37ca-392b-4219-9882-eee9ee3b2f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bc2f8208-fc20-4eef-9106-8fae9e80997b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>d069e301-d654-48c2-a0f1-2f09a97b4874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-primary</value>
      <webElementGuid>cff0031b-144b-47c0-85d2-d1b53448d60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProcessButton&quot;)</value>
      <webElementGuid>21c06520-232e-468d-a7c5-b4287d2ea684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ECMSprint3/ECM_AR/Page_Account Receivable - Easy Claims Manager/iframe_This page requires frames in order t_99ba60</value>
      <webElementGuid>b6ddb4b0-acd7-48b4-ba35-f681ab805cdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProcessButton']</value>
      <webElementGuid>23b7c590-34ea-4f02-9b40-a2f969fdec6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>e7c85276-24f2-4794-901e-2c9d28e80505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ProcessButton' and @type = 'submit']</value>
      <webElementGuid>e1fb2388-d6c9-4ba0-8c2e-c341dcf5dbe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
