<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Final Letter Sent_Idnull</name>
   <tag></tag>
   <elementGuidId>795eae53-b440-4cbd-b207-889e4b2b76f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Idnull</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Idnull']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;000-561-831-000 Engaged H08013394 Samar Provincial Hospital CAPITOL GROUNDS, BRGY 7, CATBALOGAN CITY 09173031276 IGNACIO J. PANDONG | Sherwin Juliet Lasaca Oct 22, 2024 - 01:37 PM Oct 22, 2024 - 01:38 PM Oct 22, 2024 - 01:39 PM Oct 22, 2024 - 01:40 PM&quot;i] >> internal:label=&quot;&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>691ec167-bd85-42f3-8efe-d4aee709410c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1dea3f74-07d3-474f-af4c-ec489a9e1f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-checkbox for-generateAR</value>
      <webElementGuid>a21dad82-6d51-4694-b1b7-fc45903e630b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Idnull</value>
      <webElementGuid>77f0049e-b211-463b-91e6-27d19aba30cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Idnull</value>
      <webElementGuid>dca5cdd2-e1ca-49a4-a890-7d508b21085b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Idnull&quot;)</value>
      <webElementGuid>1d5c5a27-75d2-45bd-b13c-4dd89811380a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ECMSprint3/ECM_AR/Page_Account Receivable - Easy Claims Manager/iframe_This page requires frames in order t_99ba60</value>
      <webElementGuid>0a59b007-591c-4b2b-8dcc-be5b40cc31a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Idnull']</value>
      <webElementGuid>0742c94f-0b7c-4b06-8fba-b390b6fb6bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GenerateARGrid']/div[3]/table/tbody/tr/td/input</value>
      <webElementGuid>d7469ced-02b9-4ea5-aa7a-6dd481f3c3cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>cdaaca89-5220-4910-b83a-c7e6876b6c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'Idnull']</value>
      <webElementGuid>ec04c862-523b-48a8-b591-dead821551cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
