<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Initial Letter_k-select</name>
   <tag></tag>
   <elementGuidId>bdb280cb-3ced-42d7-b3f8-87b426bf9944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='emailARLetter']/span/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;select&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c7a03de3-68ae-466c-999a-7ae86f1f0472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>397f24b6-d657-4113-804a-0bd8a069ecf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-select</value>
      <webElementGuid>b234ea32-71e5-4a35-aaf9-da01803af2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6477d772-953c-409d-9166-5c71d632c4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailARLetter&quot;)/span[@class=&quot;k-widget k-dropdown center&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-valid k-state-hover k-state-focused&quot;]/span[@class=&quot;k-select&quot;]</value>
      <webElementGuid>aa2bb88a-acc8-4a16-abeb-5db700ddd69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ECMSprint3/ECM_AR/Page_Account Receivable - Easy Claims Manager/iframe_This page requires frames in order t_99ba60</value>
      <webElementGuid>844d7c98-0641-477d-b6b7-59c574080487</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='emailARLetter']/span/span/span[2]</value>
      <webElementGuid>2eb782cd-6e81-4b10-b928-cc7e7a49c29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Initial Letter'])[2]/following::span[1]</value>
      <webElementGuid>f79d12df-2e84-4436-81cb-1f97441e8ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate AR Letter'])[1]/following::span[5]</value>
      <webElementGuid>b456e333-1a5e-4265-8d33-8b7f96b755e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]</value>
      <webElementGuid>51567503-1f43-4b39-acec-4e08854e36da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
