<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Professional Fees and Charges</name>
   <tag></tag>
   <elementGuidId>c1b4f14d-efcf-465b-aacd-e5f0533bf11f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ProfessionalsGrid']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.k-button.k-button-icontext.k-grid-add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e340fc7b-1a62-4f67-8d44-73305846b962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58cbfd8e-961b-4964-8096-8291aaa21a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-button-icontext k-grid-add</value>
      <webElementGuid>0f3f8d28-3d6c-45b1-98ea-404d15060d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>25f336a0-5c11-4344-956f-91dcd7bc5daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Professional Fees and Charges</value>
      <webElementGuid>092e92cd-f040-42f8-a965-eb828439943a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProfessionalsGrid&quot;)/div[@class=&quot;k-header k-grid-toolbar&quot;]/a[@class=&quot;k-button k-button-icontext k-grid-add&quot;]</value>
      <webElementGuid>ec8df307-f7a0-48d9-93c4-0ba04ae541b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ProfessionalsGrid']/div/a</value>
      <webElementGuid>db241e89-a758-4831-9481-6305db7a1dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Professional Fees and Charges')]</value>
      <webElementGuid>f8faaa5b-ed63-47fb-9a89-4d4fed13e3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/following::a[1]</value>
      <webElementGuid>aea8be84-1873-4f82-8a00-e3c269aae02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Second Case Rate'])[1]/following::a[1]</value>
      <webElementGuid>55f82ed9-c67e-4c39-aa97-3148a6d16fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accre Code'])[1]/preceding::a[1]</value>
      <webElementGuid>b639ba6b-d350-4e86-b31b-1635b8890b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/preceding::a[1]</value>
      <webElementGuid>984ca279-92b9-4ff0-bace-7dd26b43b3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Professional Fees and Charges']/parent::*</value>
      <webElementGuid>987de910-641a-4bbf-bd81-a065a5ecbf39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>c816efe0-3225-4f42-978f-c4c5776482fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/a</value>
      <webElementGuid>52283305-75d9-4586-9bbc-abc582b975f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Add Professional Fees and Charges' or . = 'Add Professional Fees and Charges')]</value>
      <webElementGuid>478e1072-f28d-4580-8fcb-8f0524c5c786</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
