<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Professional Fees and Charges_1</name>
   <tag></tag>
   <elementGuidId>c1cf54c6-6d54-4e08-a112-1312a982e014</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ProfessionalsGridEsoa']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ProfessionalsGridEsoa > div.k-header.k-grid-toolbar > a.k-button.k-button-icontext.k-grid-add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3dffeb7d-46dc-47a6-bf0f-067df944544b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40a8ce3d-afe2-4282-96a9-226222fdeb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-button-icontext k-grid-add</value>
      <webElementGuid>8bfb8e6a-7684-4069-b7c2-48be73741699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9a407642-74e3-43c6-8d7b-60772929cbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Professional Fees and Charges</value>
      <webElementGuid>89031bb1-bd95-4537-8821-c1fe3a23395d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProfessionalsGridEsoa&quot;)/div[@class=&quot;k-header k-grid-toolbar&quot;]/a[@class=&quot;k-button k-button-icontext k-grid-add&quot;]</value>
      <webElementGuid>63c55950-cc42-4e30-b7ca-b8fbc000dfe1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ProfessionalsGridEsoa']/div/a</value>
      <webElementGuid>6b305f1e-e306-4af6-a099-ddef87446ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Add Professional Fees and Charges')])[2]</value>
      <webElementGuid>88d8eb64-f7ed-4180-8d79-b0fe8b158b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please add at least one (1) Itemize Billing for ESOA.'])[1]/following::a[1]</value>
      <webElementGuid>4c18128d-fb9b-4652-8c8c-57a77a6d46ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₱2,000.00'])[1]/following::a[3]</value>
      <webElementGuid>5027f4d0-dbda-45ba-bb4d-3be2c77cd654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accre Code'])[2]/preceding::a[1]</value>
      <webElementGuid>28a2bca9-7863-491a-b4e7-bed36e78d099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[2]/preceding::a[1]</value>
      <webElementGuid>cc4029c7-5af2-46ab-89a6-dd16c9ba696c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>8e784ec3-1f18-4ffc-89fb-2711a26d78ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/a</value>
      <webElementGuid>2f2314cc-62b3-4934-a952-a395a7b8ba47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Add Professional Fees and Charges' or . = 'Add Professional Fees and Charges')]</value>
      <webElementGuid>0e59920b-720b-4166-9058-e29037fb8f28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
