<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Claim Form 2 (CF2)</name>
   <tag></tag>
   <elementGuidId>4c61efb3-7a89-4479-8a45-8b28476f76d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='feesChargesForm']/div[10]/div[2]/ul[2]/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul:nth-of-type(2) > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c879bed9-fa47-425b-b684-45dab4c97aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:exportForm('cf2')</value>
      <webElementGuid>60c76ed6-a014-4f2c-bc7b-644dea1dc64f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Claim Form 2 (CF2)</value>
      <webElementGuid>09f8e5d0-a336-4cb0-9716-18206f6f7278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feesChargesForm&quot;)/div[@class=&quot;form-group&quot;]/div[2]/ul[2]/li[1]/a[1]</value>
      <webElementGuid>10194ae1-374f-4d84-a68f-89cd839eab73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='feesChargesForm']/div[10]/div[2]/ul[2]/li/a</value>
      <webElementGuid>1f6c3aaa-1788-4528-9cba-e76555057cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Claim Form 2 (CF2)')]</value>
      <webElementGuid>a062e516-246e-44c1-a08b-f6c154a8c213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Below are exportable document attachments. Click to generate the specific form:'])[1]/following::a[1]</value>
      <webElementGuid>e72764b5-c9c5-486e-8917-a6f14168cafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try splitting the pages as separate files in case of inevitable attachment of a large document.'])[1]/following::a[1]</value>
      <webElementGuid>86e6c3ce-d52f-41c0-81ba-cca869bbe355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim Signature Form (CSF)'])[1]/preceding::a[1]</value>
      <webElementGuid>3b7717ef-3242-4e54-8cd5-79676e6789dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eSOA'])[1]/preceding::a[2]</value>
      <webElementGuid>b3c778a7-1130-4d15-91c4-5f1c47bbcac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Claim Form 2 (CF2)']/parent::*</value>
      <webElementGuid>666946f5-f558-4370-8781-83a7e3f13663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:exportForm('cf2')&quot;)]</value>
      <webElementGuid>a38f0d27-d8ad-48db-a986-460a063e4882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/a</value>
      <webElementGuid>8cca5496-c54d-41d4-a2a0-fd5bc8dc7a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:exportForm(&quot; , &quot;'&quot; , &quot;cf2&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Claim Form 2 (CF2)' or . = 'Claim Form 2 (CF2)')]</value>
      <webElementGuid>fc9781d2-7156-48d7-857d-5e137e83c9cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
