<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Claim Signature Form (CSF)</name>
   <tag></tag>
   <elementGuidId>1d7cadc8-9ea6-4656-a176-065ae353de95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='feesChargesForm']/div[10]/div[2]/ul[2]/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul:nth-of-type(2) > li:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6ddf5def-9a03-473f-bce3-4baf04395d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:exportForm('csf')</value>
      <webElementGuid>817d00bb-dd2f-4fea-929b-4f03198a2946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Claim Signature Form (CSF)</value>
      <webElementGuid>70e47580-5906-4bf3-9d5a-60235b21fd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feesChargesForm&quot;)/div[@class=&quot;form-group&quot;]/div[2]/ul[2]/li[2]/a[1]</value>
      <webElementGuid>22cfd629-1b23-4ab2-a5c9-07efd464ee93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='feesChargesForm']/div[10]/div[2]/ul[2]/li[2]/a</value>
      <webElementGuid>3eb2bb4a-c323-44f3-b3e9-21774112d555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Claim Signature Form (CSF)')]</value>
      <webElementGuid>7cafac69-dcd6-4a13-98e0-9ee54376299c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim Form 2 (CF2)'])[1]/following::a[1]</value>
      <webElementGuid>53d9418d-2f8f-4197-896e-4d91f321826d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Below are exportable document attachments. Click to generate the specific form:'])[1]/following::a[2]</value>
      <webElementGuid>32e7774b-20a2-4027-ba34-a43bd1a12a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eSOA'])[1]/preceding::a[1]</value>
      <webElementGuid>e46a7b62-5deb-40b7-bdf6-420516a95703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eurolink Network International Corporation'])[1]/preceding::a[2]</value>
      <webElementGuid>a1cd9eb5-9eef-4a76-806b-990ce4a6bffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Claim Signature Form (CSF)']/parent::*</value>
      <webElementGuid>2378883d-fb57-45cd-926e-1643102f148c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:exportForm('csf')&quot;)]</value>
      <webElementGuid>0969cb2c-feb7-415b-998c-a82e14806fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[2]/a</value>
      <webElementGuid>e85583c5-dc9d-4222-8460-07a63f48a26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:exportForm(&quot; , &quot;'&quot; , &quot;csf&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Claim Signature Form (CSF)' or . = 'Claim Signature Form (CSF)')]</value>
      <webElementGuid>ab9905ac-0533-4122-aeab-35a4f3f74ad4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
