<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_eSOA</name>
   <tag></tag>
   <elementGuidId>c4256859-95d3-499c-ade1-53d260e5de0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='feesChargesForm']/div[10]/div[2]/ul[2]/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul:nth-of-type(2) > li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>831265b2-9a0d-4455-b723-dd1497c36ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:exportForm('esoapdf')</value>
      <webElementGuid>2aaed3be-a2ee-4c4a-9bca-f2edcbbf4b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>eSOA</value>
      <webElementGuid>2fbe8add-cca1-4990-89c7-1b5833fcda75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feesChargesForm&quot;)/div[@class=&quot;form-group&quot;]/div[2]/ul[2]/li[3]/a[1]</value>
      <webElementGuid>c2e9110f-9564-4c33-b82f-822082184e0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='feesChargesForm']/div[10]/div[2]/ul[2]/li[3]/a</value>
      <webElementGuid>62e38949-d7cd-42b1-ab30-3f24f67d9de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'eSOA')]</value>
      <webElementGuid>80e4fe65-445d-464f-8ee4-9fee4e4b8d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim Signature Form (CSF)'])[1]/following::a[1]</value>
      <webElementGuid>2c8178bd-0ef7-4d47-8fc1-e7c0a604fff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim Form 2 (CF2)'])[1]/following::a[2]</value>
      <webElementGuid>4eccd8ef-dc5f-40e3-81b3-80bbb16443ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eurolink Network International Corporation'])[1]/preceding::a[1]</value>
      <webElementGuid>f54f04a4-37d6-4fe4-b6e9-591eacf9aa99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='eSOA']/parent::*</value>
      <webElementGuid>58e00263-3420-4831-9637-f154d6fcf4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:exportForm('esoapdf')&quot;)]</value>
      <webElementGuid>580a5119-f5bc-4fce-a68a-21345a4efd9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[3]/a</value>
      <webElementGuid>d9baa429-d1f8-408d-adb5-67d1f0802314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:exportForm(&quot; , &quot;'&quot; , &quot;esoapdf&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'eSOA' or . = 'eSOA')]</value>
      <webElementGuid>d632c306-184a-4bb1-b0c2-6755e6c8cfef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
