<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign Date_DoctorSignDate</name>
   <tag></tag>
   <elementGuidId>a26097d5-819d-408b-938b-c22f134947e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DoctorSignDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DoctorSignDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b180df24-3590-439f-92be-19e8d91a59a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2faccc6-6b09-4b31-abec-e27f17b0e8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DoctorSignDate</value>
      <webElementGuid>3a715a24-2f63-41d3-b986-6939185ffa03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DoctorSignDate</value>
      <webElementGuid>6cb1db4d-ebfb-4ba6-8fd2-9ab5e586a78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign Date</value>
      <webElementGuid>2a281c6b-3c0d-48e8-b56b-cd99ac54bcdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>cb4c86c5-cb83-4cfe-8105-acc66a1e0afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7a3f43c7-0ee1-4316-a462-65a33f015cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>9/23/2024 12:00:00 AM</value>
      <webElementGuid>078f42b2-9831-46c6-b90c-e59f7a90df01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>Thu Oct 31 2024 16:25:14 GMT+0800 (Singapore Standard Time)</value>
      <webElementGuid>f6262bec-e2d3-4a42-ae1b-ad0767a30e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>85b26831-12b4-4a38-86df-6f874d98777d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value:DoctorSignDate</value>
      <webElementGuid>b71ae958-ccb2-4b38-bb87-4a76272a71d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>M/d/yyyy</value>
      <webElementGuid>19fd1e3a-4604-45e9-8b58-3bd538e5c7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>5f72c119-7b0a-4112-b6ad-0fb1374d2fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>2df22184-2751-4714-9995-e8ab86df1bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>6b5b5529-01e2-401d-87d0-eeeac84476f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dda40c4d-91c0-4082-9cef-959b5411a6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>DoctorSignDate_dateview</value>
      <webElementGuid>cc718a9b-02da-432a-ae73-c82765174c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>54350ec3-9132-45bb-a097-dee02309a4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required-msg</name>
      <type>Main</type>
      <value>Doctor Sign Date field is required.</value>
      <webElementGuid>25233a38-e7b7-4c75-8324-c67ad430087d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>0165459f-b8af-46f3-b0d0-cd57ef7e8a27_cell_selected</value>
      <webElementGuid>762eb23c-2daa-4c08-9188-3c9ec918a3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DoctorSignDate&quot;)</value>
      <webElementGuid>7a57b19b-3a38-4b31-ada8-3bf2d4b26bbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DoctorSignDate']</value>
      <webElementGuid>713bb841-af88-4d7a-9040-90696dab3b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/span/span/input</value>
      <webElementGuid>531faf0f-3daa-4349-ae36-2ad6819dabeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DoctorSignDate' and @name = 'DoctorSignDate' and @title = 'Sign Date']</value>
      <webElementGuid>8923e9ef-4f9c-489b-a9e8-b1811431c493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
