<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date Signed_AccessPatientRecords.DateSigned</name>
   <tag></tag>
   <elementGuidId>2f898302-ab29-49b3-b1e7-6fb39baee7da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccessPatientRecords_DateSigned']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AccessPatientRecords_DateSigned</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a4df291-0333-43a9-b937-e5445ef82f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-currentdate valid-date validate-ds date-signed k-input</value>
      <webElementGuid>19132d5a-c705-4a74-92f0-f03a9c8192cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>69323a60-8530-48ba-830a-d391b83b98d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field Date Signed must be a date.</value>
      <webElementGuid>4ebc4a4b-4b21-41e9-a410-f8086e9d832a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccessPatientRecords_DateSigned</value>
      <webElementGuid>0bbd01b0-f73f-480e-8f7d-8b5f8aefbe7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccessPatientRecords.DateSigned</value>
      <webElementGuid>ae4d846e-eacc-4b47-b4b5-e60bb5afb143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78d5776c-9c77-4f59-a118-be8424450c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>176db87a-9541-4a73-9703-2ad8e0bef0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>8505de38-cd14-45e6-8358-751af48d7b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>01aae06a-affb-47b7-96a7-158f89d54159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>AccessPatientRecords_DateSigned_dateview</value>
      <webElementGuid>4fe854df-6368-4e4e-a874-99749ab0df48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>847874e5-bb5d-4016-8ce0-b83855ea83c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>89c0ed1a-959f-426e-ab94-8e22c1fee017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccessPatientRecords_DateSigned&quot;)</value>
      <webElementGuid>8965edc6-54bd-46d4-a86a-cf59ce19142d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccessPatientRecords_DateSigned']</value>
      <webElementGuid>042bdbe8-b1aa-4545-b3b1-a41cfd0369a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datesignedValidation']/span/span/input</value>
      <webElementGuid>7c14b22d-98c7-465d-a678-a4ae76383186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div/div/span/span/input</value>
      <webElementGuid>7941d944-beb2-4161-895a-7758afdc9ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccessPatientRecords_DateSigned' and @name = 'AccessPatientRecords.DateSigned' and @type = 'text']</value>
      <webElementGuid>ec996443-d583-4cc3-9ec2-cd39bd7fc24f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
