<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accre Code_DoctorAccreCode</name>
   <tag></tag>
   <elementGuidId>24399cfa-ffff-4130-b60c-10f9f3affa11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='DoctorAccreCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;DoctorAccreCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70d362a9-4998-44db-be33-4b239092fdd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DoctorAccreCode</value>
      <webElementGuid>7116acec-193c-4396-bbe1-b40eb510e3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-numeric maskedtextbox-dash k-textbox</value>
      <webElementGuid>f84e12ea-13bb-4bb8-b9f1-298ab1a1bf93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>maskedtextbox</value>
      <webElementGuid>cccec69d-537b-4b65-90e2-44be99be0740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4e866ead-caa4-4b92-96dc-f28bd790d085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value:DoctorAccreCode</value>
      <webElementGuid>05c6e0e1-672a-4791-b367-9855739d1017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required-msg</name>
      <type>Main</type>
      <value>Doctor Accre Code field is required.</value>
      <webElementGuid>da726b59-38df-4b27-9058-5f4060f40c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;k-webkit k-webkit130 js&quot;]/body[@class=&quot;k-content&quot;]/div[@class=&quot;k-widget k-window&quot;]/div[@class=&quot;k-popup-edit-form k-window-content&quot;]/div[@class=&quot;k-edit-form-container&quot;]/div[@class=&quot;k-edit-field&quot;]/span[@class=&quot;k-widget k-maskedtextbox input-numeric maskedtextbox-dash&quot;]/input[@class=&quot;input-numeric maskedtextbox-dash k-textbox&quot;]</value>
      <webElementGuid>4db50b2a-1806-4809-9e7f-aaf9fb975373</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='DoctorAccreCode']</value>
      <webElementGuid>61f0171a-e255-417c-b3d7-07e0c092fe28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/div/div[2]/span/input</value>
      <webElementGuid>e2db2c30-b886-4c2f-807b-ae5c4e260347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'DoctorAccreCode']</value>
      <webElementGuid>5e05f990-e795-4d78-95b4-09ca2ae4103d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
