<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Consumption_EnoughBenefits_Default_Co_454067</name>
   <tag></tag>
   <elementGuidId>fab51682-d7b0-4057-a1f0-a5f062bb34ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Consumption_EnoughBenefits_Y']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Consumption_EnoughBenefits_Y</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>513c0b16-b8df-4bc2-aa79-7c48061abb64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-radio consumptionEnoughBenefits</value>
      <webElementGuid>eca9f89a-51b2-4719-815f-d036af3118a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>916c3c57-daa6-4ba9-a111-7486fca42135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Consumption_EnoughBenefits_Y</value>
      <webElementGuid>e6dd13e9-1229-41cc-b3da-e7e4b33ad660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Consumption.EnoughBenefits</value>
      <webElementGuid>81d9d478-f059-4e4f-a982-6559a4868f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>enoughBenefits_change()</value>
      <webElementGuid>0cfa9cfa-f90b-4ab0-a70b-fd8d1913a68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0d64180e-671d-4c43-b09c-5dcddae0e252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>df4f8003-05a0-41d7-aa53-e3f00d39238f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Consumption_EnoughBenefits_Y&quot;)</value>
      <webElementGuid>07a8f6fa-4003-41f2-92ea-4bee7ea0a357</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Consumption_EnoughBenefits_Y']</value>
      <webElementGuid>3364fc48-5ca1-4e65-9da6-31a74251a7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='benefitsForm']/div/div/input[2]</value>
      <webElementGuid>837a571e-5ab8-44a0-998a-a4abf901c546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>ea1548d0-e4b5-43ef-8893-ff1359d44c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Consumption_EnoughBenefits_Y' and @name = 'Consumption.EnoughBenefits' and @type = 'radio']</value>
      <webElementGuid>acab8489-63f6-4a12-996c-8e489426cc51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
