<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ICD Code_FirstCaseRate.ItemCode_input</name>
   <tag></tag>
   <elementGuidId>3be19d02-c75a-4458-85f6-932bfaea8e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='FirstCaseRate.ItemCode_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;FirstCaseRate.ItemCode_input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c90bf637-c168-48f1-ba45-4039e39bd24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FirstCaseRate.ItemCode_input</value>
      <webElementGuid>8ae048e5-c276-4bc3-8117-9ebf1c02849d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>331483b9-4364-4825-b905-7a3a7dc16d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f54c0892-cb87-47e4-bb06-fc26163461b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ca6f39d6-4420-4c4e-8822-bee172d869bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>215ac3d7-4d70-4beb-8425-90a7e4e9c890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f16bc922-5b4c-4347-b515-615342922883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Code</value>
      <webElementGuid>808ddc4a-9024-4851-bdbb-4f1ea8f734f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e666f247-e673-4b92-8753-e70b27ae0112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>21f36eeb-3f74-44c9-81ed-bcecf0d1eb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>a4d2551a-3a10-4adc-b14e-2bf44f7d8bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>FirstCaseRate_ItemCode_listbox</value>
      <webElementGuid>2d612348-0384-427a-8b8e-6fecb10f7c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-busy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>13a090ce-5ca5-45ed-8972-b12d90393b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>a2d79b40-2e8d-4db8-8bd3-cd474fdc1768</value>
      <webElementGuid>8349386b-6f77-4caf-b6b0-3e60a25c181c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemcodeValidation&quot;)/span[@class=&quot;k-widget k-combobox k-combobox-clearable k-state-border-down&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-focused k-state-active k-state-border-down&quot;]/input[@class=&quot;k-input&quot;]</value>
      <webElementGuid>375f029d-d363-48c1-bc5b-031bfc2626db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='FirstCaseRate.ItemCode_input']</value>
      <webElementGuid>cfc0a140-3aa6-4569-867e-2cf5fde7db98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='itemcodeValidation']/span/span/input</value>
      <webElementGuid>45969374-40df-48a8-941c-45e9d63f582c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>4c565c76-f7cd-4011-abdb-47f4df13516c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'FirstCaseRate.ItemCode_input' and @type = 'text' and @placeholder = 'Item Code']</value>
      <webElementGuid>16197dc8-786b-4ef5-b615-e14951f54aec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
