<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AccessPatientRecords_APRType_Default__6e28a2</name>
   <tag></tag>
   <elementGuidId>8c99437e-18a1-4865-b08d-2eec42048b94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccessPatientRecords_APRType_Patient']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AccessPatientRecords_APRType_Patient</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>070ef87e-a1fa-4dda-83ef-0840091ecab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-radio AccessPatientRecordsAPRType</value>
      <webElementGuid>d65ef0e5-92ee-4d42-9d3d-ec1639c22750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3b273c91-bd8c-45e2-a9b0-7d410d97740c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccessPatientRecords_APRType_Patient</value>
      <webElementGuid>c804528f-b02a-4c46-8eb7-59b2a8e9c168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccessPatientRecords.APRType</value>
      <webElementGuid>22dbde8b-a18c-4267-a768-8296379bb5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aprType_change()</value>
      <webElementGuid>3ecad7c4-4c4f-4420-88e4-866bc08b80bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>67b6a211-e902-452d-a69c-788c7fe0f950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>d0c412e4-da62-4c19-8edf-36dd09ff7dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccessPatientRecords_APRType_Patient&quot;)</value>
      <webElementGuid>faaf501d-e76e-4b14-9f32-b78099f2c300</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccessPatientRecords_APRType_Patient']</value>
      <webElementGuid>36cc4a75-130f-48e9-8dba-a3f3ff37a118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='consentValidation']/input[2]</value>
      <webElementGuid>0bbfe62c-cf6e-48e6-8d57-830cf131d3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input[2]</value>
      <webElementGuid>03bbbf3b-7046-47be-96da-5ed42b72004e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccessPatientRecords_APRType_Patient' and @name = 'AccessPatientRecords.APRType' and @type = 'radio']</value>
      <webElementGuid>d9c4f557-f122-4640-95a9-eec61bbc4e20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
