<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Consumption_EnoughBenefitsEsoa_Defaul_ded43e</name>
   <tag></tag>
   <elementGuidId>9b0e9f33-2bd6-4152-9719-167a314abe63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Consumption_EnoughBenefitsEsoa_Y']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Consumption_EnoughBenefitsEsoa_Y</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ff84829-1cf8-4908-8193-ef1e04bd4016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-radio consumptionEnoughBenefits</value>
      <webElementGuid>dbfb62a1-82f6-48c8-9a96-7b4692379f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b4065607-87b4-4b31-afb4-915f6306eb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Consumption_EnoughBenefitsEsoa_Y</value>
      <webElementGuid>cf9fda50-7fb2-43ce-80e4-bfe635a6507c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Consumption.EnoughBenefitsEsoa</value>
      <webElementGuid>6b159968-d527-458f-af20-0c66851e50eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ESOA_enoughBenefits_change()</value>
      <webElementGuid>24e9ca37-0d47-494b-93ee-26518863ae28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>893bb5d5-2e79-46c1-9b82-dce805875a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>8011e7b2-ec28-4ba0-9874-4734a62ff00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Consumption_EnoughBenefitsEsoa_Y&quot;)</value>
      <webElementGuid>794fff33-71b2-4d1e-935d-34d079fcef96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Consumption_EnoughBenefitsEsoa_Y']</value>
      <webElementGuid>d7d46682-c483-44f9-9370-48d878252a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='enoughbenefitsForm']/div/div/div/input[2]</value>
      <webElementGuid>3f903427-d221-4977-8e66-8c302a467718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/input[2]</value>
      <webElementGuid>5b3c4a49-8a15-4b45-b806-3d8115b99912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Consumption_EnoughBenefitsEsoa_Y' and @name = 'Consumption.EnoughBenefitsEsoa' and @type = 'radio']</value>
      <webElementGuid>1b43832d-6593-48a5-ad9f-5bf2753e4492</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
