<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_All Case Rate</name>
   <tag></tag>
   <elementGuidId>7e5252e9-1b58-4e22-89fd-1179c616dd29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='c757e828-ef19-4fc4-b074-b7374195d976']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c757e828-ef19-4fc4-b074-b7374195d976</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c7774e76-d8c1-4169-b6fd-46093c4515e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>aa507d22-bfa2-46f0-9ed5-49dfe8b005a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e2476a98-1e94-4cc7-b06a-4de9c5d649bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>eccd8846-880a-494e-8ab5-ae55561e7378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-selected k-state-focused k-state-hover</value>
      <webElementGuid>670a3bc1-4fc4-44b4-b61c-42c333dd21ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7b3d1837-12aa-4385-8b17-08271dcff48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>38648572-e67e-4ba2-9ad4-cf4cc2f5aff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c757e828-ef19-4fc4-b074-b7374195d976</value>
      <webElementGuid>fdc14635-90de-413c-954d-1dc2873b418a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Case Rate</value>
      <webElementGuid>b25a7a8e-3814-4d76-bccf-41eb416d23e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c757e828-ef19-4fc4-b074-b7374195d976&quot;)</value>
      <webElementGuid>045e5d50-c2b8-4647-968b-601246e90b23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='c757e828-ef19-4fc4-b074-b7374195d976']</value>
      <webElementGuid>a6690fd0-4f86-4fc5-a3d0-312521016166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ClaimType_listbox']/li</value>
      <webElementGuid>e9691c33-efa8-4a07-99c7-3d18d2e473cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select One'])[2]/following::li[1]</value>
      <webElementGuid>7485b32f-7fb9-40e5-a41e-9b519fd740a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate'])[1]/following::li[1]</value>
      <webElementGuid>ad14aea3-f224-4b2b-86cb-0a9265278b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Z-Benefit'])[1]/preceding::li[1]</value>
      <webElementGuid>2678af6d-f231-48a4-8266-4eb6ad1ca27a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[1]/preceding::li[2]</value>
      <webElementGuid>1ad83096-a311-4816-b7b3-f94c29d60fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li</value>
      <webElementGuid>ebba52d4-de56-4625-9b52-dce0f0d117df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'c757e828-ef19-4fc4-b074-b7374195d976' and (text() = 'All Case Rate' or . = 'All Case Rate')]</value>
      <webElementGuid>110055d8-b164-4827-bc87-50462aa0a941</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
