<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_All Case Rate_k-icon k-i-arrow-60-down</name>
   <tag></tag>
   <elementGuidId>4edd2d9b-d775-4ac0-b5da-92c9414b06b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='claimtypeValidation']/span/span/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.k-icon.k-i-arrow-60-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>55c257d8-06cf-4d8f-8996-c11eea9be788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-60-down</value>
      <webElementGuid>591022df-0259-4ddb-b126-0146adcf5836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;claimtypeValidation&quot;)/span[@class=&quot;k-widget k-dropdown dropdownlist-claimType&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-hover k-state-focused&quot;]/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-60-down&quot;]</value>
      <webElementGuid>85a199e1-394d-4dbd-a03a-b2d4e83dd7d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='claimtypeValidation']/span/span/span[2]/span</value>
      <webElementGuid>501777a5-4b0a-4fb5-b77d-896ae8ddb3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]/span</value>
      <webElementGuid>d7dd8285-e230-4943-9c32-f5118d8901e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
