<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Reports</name>
   <tag></tag>
   <elementGuidId>bb9b5fb0-cc04-47e2-8324-da4fec7ab84a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.flex-cell.commandbar-item-link.flex-grow.no-child.fa- > span.flex-grow.commandbar-item-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reports-nav']/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Reports&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d8f028f3-7df3-43e0-8089-18ed240f0fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-grow commandbar-item-text</value>
      <webElementGuid>49300949-bb8a-40ed-aeac-49056f18c659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reports</value>
      <webElementGuid>54f75bc3-a16e-44e7-bc7c-0b0a47e91e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reports-nav&quot;)/a[@class=&quot;flex-cell commandbar-item-link flex-grow no-child fa-&quot;]/span[@class=&quot;flex-grow commandbar-item-text&quot;]</value>
      <webElementGuid>cbe950b0-eb84-4475-bfd9-06df593988d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reports-nav']/a/span[2]</value>
      <webElementGuid>db49f4ad-c844-4f5e-b4a3-e38742cc2816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collection'])[1]/following::span[4]</value>
      <webElementGuid>8ce1d826-f89f-46d4-8386-34023af399b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing'])[1]/following::span[8]</value>
      <webElementGuid>ddca67ba-d3f7-44b7-a86c-ffcd3b072828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts Receivable'])[1]/preceding::span[4]</value>
      <webElementGuid>47153754-3bf4-4af2-8696-f4d9a4a7fc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Statement'])[1]/preceding::span[8]</value>
      <webElementGuid>6700ce6b-635a-4e88-9dca-2a4390fcbca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reports']/parent::*</value>
      <webElementGuid>18636cda-4aee-4438-8112-df601bfef4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/a/span[2]</value>
      <webElementGuid>89690236-6fac-4f21-8d4c-01841445edb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Reports' or . = 'Reports')]</value>
      <webElementGuid>df28426c-a23c-4797-a9e9-5508134db399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
