<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_samplegmail.com_addUserBtn</name>
   <tag></tag>
   <elementGuidId>410a1f96-bf49-443e-9971-890689437ed1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addUserBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addUserBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add User&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff836c2c-a8e9-4208-8f8f-10a20f66dd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addUserBtn</value>
      <webElementGuid>2cdf72a9-f993-4743-af62-99aa20eb7330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c562342-ca6a-4b64-aee0-ddee1430a530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add User</value>
      <webElementGuid>6ae3617b-b11a-4ea3-ad6a-08f5916f8b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-primary</value>
      <webElementGuid>9ea18a80-e976-4643-93cd-a339ceb6909d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addUser()</value>
      <webElementGuid>84664dd6-ac28-4349-8eb6-398134ad6f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addUserBtn&quot;)</value>
      <webElementGuid>7ffc929d-d9fa-4585-96e4-a0788b4fa36a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addUserBtn']</value>
      <webElementGuid>50f3a468-1944-42b0-8cbc-aa20bb80a5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='control-panel']/li[2]/div/p/input</value>
      <webElementGuid>9f027b4f-cc36-4e29-9471-2419f585bfb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>13dbac8f-fe23-48fb-8e8b-2e38bfac7b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addUserBtn' and @type = 'button']</value>
      <webElementGuid>3947a67e-e984-4096-b719-73eca20a9df2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
