<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_St. Peter Claver Hospital</name>
   <tag></tag>
   <elementGuidId>3d9df8d0-2b83-4f37-b2df-ff6609748d39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.k-item.k-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='HospitalInformationId_listbox']/li[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;St. Peter Claver Hospital&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c06e1ee9-f815-4027-8c61-78376b621d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0869183f-0df8-455d-9964-d9e95c625ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>4f8b1486-13cb-4981-9d67-d364f05b9ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>5b1d9bde-cb83-4099-b4fc-35609f3ba251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-hover</value>
      <webElementGuid>5043011d-488f-46e0-8ce2-0c9ae58d87d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c844ba24-886e-4337-8d02-81a58a38624d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>20d06b30-73a9-4b42-8338-ddf9141f0c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>St. Peter Claver Hospital</value>
      <webElementGuid>27feacbe-9aab-422a-ac8b-e746fc39e16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HospitalInformationId_listbox&quot;)/li[@class=&quot;k-item k-state-hover&quot;]</value>
      <webElementGuid>66e9e49d-c2c1-4357-9248-acdeaea66e94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='HospitalInformationId_listbox']/li[7]</value>
      <webElementGuid>c3e7375b-ee5d-42c6-bc0f-4c1dc5e21b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mapandan Community Hospital'])[2]/following::li[1]</value>
      <webElementGuid>ba0e9091-a862-4b9c-8e4d-d548afb60af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queensrow Central Maternity and Lying-In Clinic'])[2]/following::li[2]</value>
      <webElementGuid>8db3aa10-97cc-4909-bd68-03083910fd2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[2]/preceding::li[1]</value>
      <webElementGuid>3201ec81-6488-4a9c-b2cb-7a3feca23e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[9]/preceding::li[1]</value>
      <webElementGuid>721b997d-c930-464d-9563-fe5bb080114c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[7]</value>
      <webElementGuid>ab0e289e-ec14-488d-8846-43a5f47a496b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'St. Peter Claver Hospital' or . = 'St. Peter Claver Hospital')]</value>
      <webElementGuid>6b427190-f0c0-48b3-ab0e-3bee4ce1905f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
