<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PIN_MemberPIN</name>
   <tag></tag>
   <elementGuidId>e2d9622d-e042-40d7-b389-ad239f9b98a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MemberPIN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MemberPIN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;PIN*&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e69c4cd-71c9-4650-b9e7-1c993b26e687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-numeric maskedtextbox maskedtextbox-dash src-patient-info k-textbox</value>
      <webElementGuid>56c35801-4c21-4942-98ed-308f62d18b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>774c8028-fe15-4e85-92bb-0e729292e643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The Member PIN field can only have a maximum of 12 character(s).</value>
      <webElementGuid>109c9040-c54a-47c5-ae7d-d97f320e7403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>3d327717-51f3-411b-8ec3-f69eb7229274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Member PIN field is required.</value>
      <webElementGuid>7ea37088-3517-4ae2-b01f-b9ce52d81ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MemberPIN</value>
      <webElementGuid>0ae6bd86-cb24-4d35-8c9b-d85d34c58b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MemberPIN</value>
      <webElementGuid>a84ccf6f-341d-4d98-889f-f21da31633a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>maskedtextbox</value>
      <webElementGuid>638b6abd-f76c-4527-b089-d8dd91be9b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>251883fb-c37f-4d32-9d26-f74464278ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MemberPIN&quot;)</value>
      <webElementGuid>41cd4865-8c03-40fd-8605-489d9ed9f1e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MemberPIN']</value>
      <webElementGuid>f7910f06-e753-4adc-8a36-f4bde5f69895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pinValidation']/span/input</value>
      <webElementGuid>9cfae21f-3bcb-4d5f-9003-b2962871c3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[4]/div/span/input</value>
      <webElementGuid>fee50c96-0186-478b-b58f-15fe82746629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MemberPIN' and @name = 'MemberPIN']</value>
      <webElementGuid>e351c52e-8aa5-4ede-a0f6-ec707e116bd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
