<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_ZipCode</name>
   <tag></tag>
   <elementGuidId>9ed67647-6f4c-4758-90b2-84bca285b976</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ZipCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ZipCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Zip Code&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be20a7f4-749f-4d37-afc0-626acee32501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>maskedtextbox input-numeric k-textbox-sm k-textbox</value>
      <webElementGuid>bedd6c65-94ff-4127-8627-62ca7a834534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3e607ead-7af6-4380-8424-e92a185f1550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The Zip Code field can only have a maximum of 4 character(s).</value>
      <webElementGuid>b87da68f-2405-470d-b93b-e08334ad40c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>9cfb3946-7a21-484d-b585-02fb392b922f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Zip Code field is required.</value>
      <webElementGuid>ec24a03e-b10f-49ad-9e42-cdde8e5b7a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ZipCode</value>
      <webElementGuid>0f176198-f87c-45be-a7c3-5467520f7d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ZipCode</value>
      <webElementGuid>260fb83b-0b52-4614-aa11-cc61997c39bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>maskedtextbox</value>
      <webElementGuid>177bc418-9f3a-40e8-b73f-9d46a850d157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8a23925a-d9d6-4145-9f21-926bb6c65aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ZipCode&quot;)</value>
      <webElementGuid>822c7a23-ae87-458e-b352-693009ce39b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ZipCode']</value>
      <webElementGuid>34833efc-b3ce-45fc-a5c7-5aab3e191d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zipcodeValidation']/span/input</value>
      <webElementGuid>8e67ea63-486e-4a3d-8050-e27afe26cffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>cb7ef151-5c02-4d29-901b-ce2627c345ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ZipCode' and @name = 'ZipCode']</value>
      <webElementGuid>6876fe81-04a4-4537-ad8b-c13055ac698b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
