<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MemberGender_DefaultMaleFemale</name>
   <tag></tag>
   <elementGuidId>a80ad032-0ea4-4f3e-b233-30d817a6314d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='genderValidation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#genderValidation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ca88dbdb-58bb-4e91-b456-facc9f99b1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-12</value>
      <webElementGuid>14a8b479-6858-4517-ba40-410463c54ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>genderValidation</value>
      <webElementGuid>0a3c96ca-30f0-41af-b7db-60ebb4afa809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                MemberGender_DefaultMaleFemale
            </value>
      <webElementGuid>79451c38-c0e1-4272-86a7-9016ac85250e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;genderValidation&quot;)</value>
      <webElementGuid>800287c9-7d20-4fb5-9ecb-9ce04278ce0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='genderValidation']</value>
      <webElementGuid>70da6a6e-18e7-4908-b815-ee1472ef67e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='genderForm']/div</value>
      <webElementGuid>e98b2c33-058c-448a-8942-bf96a3542f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::div[1]</value>
      <webElementGuid>f5d185d1-bc62-4a03-acc4-8ef24bd4eb62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::div[3]</value>
      <webElementGuid>ae4e76db-e01c-47eb-b8f5-36d6bae39d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[3]/div</value>
      <webElementGuid>639bea0b-0ec5-468e-9c3d-dd6406c75869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'genderValidation' and (text() = '
                MemberGender_DefaultMaleFemale
            ' or . = '
                MemberGender_DefaultMaleFemale
            ')]</value>
      <webElementGuid>7e50abc9-c766-45c6-a24a-98fcee07dfb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
