<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PIN_MemberPIN</name>
   <tag></tag>
   <elementGuidId>6871d7b9-6160-4e85-afb8-443c1e5b6cf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MemberPIN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MemberPIN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79de0150-9c40-40c6-840d-0dd5220d142c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-numeric maskedtextbox maskedtextbox-dash src-patient-info k-textbox</value>
      <webElementGuid>f9ba94e9-7313-48d1-af8d-52d17804c32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ebb1b957-0bcf-4c26-8304-964ad35bf93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The Member PIN field can only have a maximum of 12 character(s).</value>
      <webElementGuid>1cc05e1b-bd89-496d-b491-2108bbf32081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>234bac61-11f5-4606-874c-f0e94c4775fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Member PIN field is required.</value>
      <webElementGuid>60cfb4ea-ff25-4939-9e23-45f1bea45d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MemberPIN</value>
      <webElementGuid>4212c790-8103-4bb2-8cc0-5e742cca0207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MemberPIN</value>
      <webElementGuid>192e579c-88e7-45de-b69f-f0ef3caeaf4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>maskedtextbox</value>
      <webElementGuid>0e9e8ec0-1909-4073-94fe-c25a137c1b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6be85f81-ed72-47d0-8bf1-d05cdd99f46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MemberPIN&quot;)</value>
      <webElementGuid>318750c4-b1f1-4d54-9d47-7ad80b4c9150</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MemberPIN']</value>
      <webElementGuid>904526af-bdba-4489-8c2b-5b917d50b459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pinValidation']/span/input</value>
      <webElementGuid>cfc8c853-cdab-4c4f-86e6-7d1589ebde47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[4]/div/span/input</value>
      <webElementGuid>fef8c924-38bc-43a2-a759-7f98f1db8214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MemberPIN' and @name = 'MemberPIN']</value>
      <webElementGuid>832c9e95-2b64-46e5-8814-6780f9f62252</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
