<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_The Member Last Name field is require_ace58e</name>
   <tag></tag>
   <elementGuidId>a4c5bf20-e533-4148-ab22-01780963b19e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MemberFirstName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MemberFirstName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>051f02d1-1591-4886-a5ba-5c722802373a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-name  required-field src-patient-info k-input k-invalid</value>
      <webElementGuid>3b532282-d3f6-4042-aeec-4d6a281997eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f150f578-4e55-45bc-833d-a879e298615c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The Member First Name field can only have a maximum of 60 character(s).</value>
      <webElementGuid>42d8b40b-a69c-46aa-b97f-961aad14222d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>02f3d882-96a6-47a5-a1ac-361b8a30f5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Member First Name field is required.</value>
      <webElementGuid>872a3014-2e8e-45c6-9bef-8c0fa9fba943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MemberFirstName</value>
      <webElementGuid>2594d027-b3e6-420f-93a4-bfa5cfd6ab87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MemberFirstName</value>
      <webElementGuid>31b14ba5-782e-4a9c-84c1-18b93c06f306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>FIRST NAME</value>
      <webElementGuid>27e0fb21-30cd-4a93-9598-b2c2ef2251a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LEILANI</value>
      <webElementGuid>d48d4de0-c8b0-41fe-b16b-e2569584b0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b65d869e-f71a-4de3-a0dc-b0295fa208db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>23ef1d80-84da-4b85-99ad-c532e0f304d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>816afd61-3748-4c47-81b0-4bb116ec6e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7ecd6899-7a51-4fac-8753-5966a80a1b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>MemberFirstName_validationMessage</value>
      <webElementGuid>1e6fb7a0-31a4-4680-b316-fde5b19eb307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MemberFirstName&quot;)</value>
      <webElementGuid>ae594913-a40e-486c-b8f3-bc821ef26b51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MemberFirstName']</value>
      <webElementGuid>d1a67cac-09cf-4154-b33c-72dbcead455c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='firstnameValidation']/span/input</value>
      <webElementGuid>b8706a23-f5e1-41c4-adb0-1f057ab5bee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>896289de-43e4-4990-8eda-47eb3a9bff4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MemberFirstName' and @name = 'MemberFirstName' and @placeholder = 'FIRST NAME']</value>
      <webElementGuid>6329cc4c-0599-4651-9d99-46d40e1c081b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
