<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Discharge Date and Time_DischargeDateTime</name>
   <tag></tag>
   <elementGuidId>1c01730b-03c3-4b5f-b1cb-7de3e59f7c80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DischargeDateTime']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DischargeDateTime</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46803d37-eb05-44a2-8a8f-73ec59654de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>range-date k-input</value>
      <webElementGuid>6058a7a1-1161-492f-8e3e-0c685bc5a054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d9e1f6d3-395a-4c45-ab30-4c976a3fbc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field Discharge Date and Time must be a date.</value>
      <webElementGuid>ac5ed286-728f-4045-8081-bb88672d217a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DischargeDateTime</value>
      <webElementGuid>1ca9a27b-43bb-4c0e-9a03-b75f5e1a72c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DischargeDateTime</value>
      <webElementGuid>ab7e9394-a004-4602-a3da-000174ca3fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04db0512-b26f-4edc-a94f-60a4bf8ea5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>datetimepicker</value>
      <webElementGuid>43e8666d-a787-4019-b0bf-cf6988e8b6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>83f51124-9df5-4733-9f18-6aefc4cf455e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4c615957-6771-41b8-9854-912beb453778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1dee0f82-528e-4b27-8bb5-179af22e5d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DischargeDateTime&quot;)</value>
      <webElementGuid>251bfca1-0854-436d-b9dd-1b851778d01e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DischargeDateTime']</value>
      <webElementGuid>3c6f04af-ff25-4683-a308-64692e5f47d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='eligibilityForm']/div[9]/div/span/span/input</value>
      <webElementGuid>50f4a11c-303a-40c8-92b3-395ccd22dcf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/span/span/input</value>
      <webElementGuid>ab2b3723-6af1-415c-ad71-d19e478cdf30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DischargeDateTime' and @name = 'DischargeDateTime' and @type = 'text']</value>
      <webElementGuid>fb28f6e9-3090-407c-bc32-fc96f0a73d3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
