<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_The Member First Name field is requir_80ac0e</name>
   <tag></tag>
   <elementGuidId>edef704d-da49-4da3-9992-2137d51dabf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MemberMiddleName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MemberMiddleName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb30707d-33f9-44f7-9a10-c6c305f752f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-name  required-field src-patient-info k-input k-invalid</value>
      <webElementGuid>b1f94e52-baa7-453a-b5a4-849bb2347749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>080c0f5a-8f77-4036-996e-1f12ecb45b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The Member Middle Name field can only have a maximum of 60 character(s).</value>
      <webElementGuid>d91ce321-cc21-4821-adaf-4fb434c9608e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>002875e2-27bc-4e33-be30-3a53c59f81a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Member Middle Name field is required.</value>
      <webElementGuid>6eed42f0-13b9-433d-95ac-38010e376a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MemberMiddleName</value>
      <webElementGuid>c7d0141b-67ec-4d5c-b021-0c36b69abccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MemberMiddleName</value>
      <webElementGuid>b381331d-f0b2-48f5-a1c1-c91d4203fc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MIDDLE NAME</value>
      <webElementGuid>a210ee75-8d8f-4a8b-8a92-ea81191150a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BALLESTEROS</value>
      <webElementGuid>952bf764-e572-4bf1-ad54-ebec4e549b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>f62d7077-d0d8-4bb7-94d4-c7d961d0226f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8d9324e7-ea57-4da6-b91f-4599dcfdd9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>544113fb-9b72-4c08-b124-e893930012bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d5e6a93-1bd8-403a-bcfc-965771885fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>MemberMiddleName_validationMessage</value>
      <webElementGuid>d325f888-27c3-49fc-9007-29ffdefa6aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MemberMiddleName&quot;)</value>
      <webElementGuid>224f091d-33b9-491e-ae4a-e00788a1839e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MemberMiddleName']</value>
      <webElementGuid>1657c2ff-8d19-4971-be30-f43b0f152879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='middlenameValidation']/span/input</value>
      <webElementGuid>7701b411-3aeb-478f-9c0b-97bcb9c84334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/input</value>
      <webElementGuid>ad757472-4bb7-423a-94e1-c178aabaeb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MemberMiddleName' and @name = 'MemberMiddleName' and @placeholder = 'MIDDLE NAME']</value>
      <webElementGuid>1b981339-331d-4c27-b6b2-846dcb93f4f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
