<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Save for E-Claims_IsFinal</name>
   <tag></tag>
   <elementGuidId>608f217d-a29b-4798-89b3-efe3a337b84e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IsFinal_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IsFinal_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6eda48e-5788-4d1b-8835-cf8e50aa978e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-radio isFinal</value>
      <webElementGuid>ead651c6-489f-4747-b113-f07eb37f1d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>89a88a64-3097-44ef-a0b9-e2c99dd04c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Save for E-Claims field is required.</value>
      <webElementGuid>7c737bc9-09b7-4c67-aa71-a748e15946c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsFinal_1</value>
      <webElementGuid>1aeab913-3493-48eb-9ab4-335303e686bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsFinal</value>
      <webElementGuid>e17e4ed9-378d-40f1-be96-16f8d3a170fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ab8656ac-c641-495e-b16c-e7521028b5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7ab68e1c-6ad8-4712-b9ba-b1afb34c24fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IsFinal_1&quot;)</value>
      <webElementGuid>16dbd111-9a3a-42b4-ac53-1982b6a8775c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IsFinal_1']</value>
      <webElementGuid>c7870ab0-d6ae-4fb8-a17f-4da4021576d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='eligibilityForm']/div[10]/div/input</value>
      <webElementGuid>907d2d1e-7b25-4f1a-a18c-52f611378e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>00d0a28c-ad94-45a2-b7e3-8071b7f9c463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IsFinal_1' and @name = 'IsFinal' and @type = 'radio']</value>
      <webElementGuid>2bef9876-7578-4034-9927-110b22d8efaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
