<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Medicine</name>
   <tag></tag>
   <elementGuidId>4af462ac-ccde-4022-861a-c1988c6a2eb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='medicine-nav']/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.flex-cell.commandbar-item-link.flex-grow.no-child > span.flex-grow.commandbar-item-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>35a6f7a0-2ab4-40c4-ac52-699a0923cef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-grow commandbar-item-text</value>
      <webElementGuid>0ca3c05e-1305-4eea-9c0e-a07087b25dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medicine</value>
      <webElementGuid>c0c20529-15b6-4d25-9c4a-6ce22fd7a009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;medicine-nav&quot;)/a[@class=&quot;flex-cell commandbar-item-link flex-grow no-child&quot;]/span[@class=&quot;flex-grow commandbar-item-text&quot;]</value>
      <webElementGuid>91f10b47-fc59-4f6b-83a5-c01317c0cad1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='medicine-nav']/a/span[2]</value>
      <webElementGuid>50edbed1-a8e4-4c62-b453-d3dfd1aca614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Claim'])[1]/following::span[4]</value>
      <webElementGuid>2b180208-c84f-4214-a1a9-b2a9fcfe9685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim List'])[1]/following::span[8]</value>
      <webElementGuid>34a62159-e524-4a71-8cd5-a7422ec7cf3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advisories'])[1]/preceding::span[5]</value>
      <webElementGuid>058e97fe-ad55-48ef-9a95-312c1800ace9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect'])[1]/preceding::span[10]</value>
      <webElementGuid>a9b9c253-c5dc-441b-8ad7-be3b61fb95e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Medicine']/parent::*</value>
      <webElementGuid>0247b0e5-74d3-4efb-bac7-bd587c3faa35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a/span[2]</value>
      <webElementGuid>37905f1a-5970-45c5-8504-06eb2a99e1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Medicine' or . = 'Medicine')]</value>
      <webElementGuid>a7cd249a-4713-46a0-b4dc-94b8a49c8134</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
