<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Mailing Address_MailingAddress</name>
   <tag></tag>
   <elementGuidId>ac484751-f36d-4676-a676-68ecd192e207</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='MailingAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MailingAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a854ed07-99bf-4bea-b416-8433e4b84407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-textbox k-textbox-lg</value>
      <webElementGuid>37f3542c-f67d-4200-beeb-980f97bf3bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>d575762b-6f29-4304-967a-7a5ee4984ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d078aa5d-e064-46e5-a386-c1ea1b764dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The Mailing Address field can only have a maximum of 150 character(s).</value>
      <webElementGuid>57043fe1-f591-4ea0-8f45-d84b607fb17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>f1c36db7-8e97-48b2-be6d-7ac8004d79ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Mailing Address field is required.</value>
      <webElementGuid>2143865a-7abf-4fe4-98c8-d5f61bf88d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MailingAddress</value>
      <webElementGuid>764056f8-94ff-4db7-845f-78c69d2f5a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MailingAddress</value>
      <webElementGuid>a2bd33be-46b2-4479-8a01-8ca9e4bb5612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>412d39ad-15f7-4451-9347-d55c8395813a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MailingAddress&quot;)</value>
      <webElementGuid>0869f3cc-f1a0-4814-a6a6-8106c5d43bec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='MailingAddress']</value>
      <webElementGuid>5c2cc9f3-60b6-4d1a-a244-de2aaf84c2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mailaddressValidation']/textarea</value>
      <webElementGuid>d9d06ea8-be82-4512-b23d-3bf6730c386d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>27479a51-108e-404a-8c25-72745bf2a468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'MailingAddress' and @name = 'MailingAddress']</value>
      <webElementGuid>e7509aef-b949-49d2-a9e3-73a25affa2cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
