<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_k-button k-primary_1</name>
   <tag></tag>
   <elementGuidId>9bd30955-73be-4b84-9951-10fd5609bf43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(20) > div.flex-list-action > input.k-button.k-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Save'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb573171-422c-4ad0-b077-f4846a5d2dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cec8e746-3ed4-43ad-a19e-7174e56c05e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>e0069f27-1fe9-4871-8f9a-ff6edae82fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-primary</value>
      <webElementGuid>eb80fb47-dfa7-49d4-bc80-3bad04123a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hospitalInfoForm&quot;)/ul[@class=&quot;flex-list&quot;]/li[20]/div[@class=&quot;flex-list-action&quot;]/input[@class=&quot;k-button k-primary&quot;]</value>
      <webElementGuid>8af3d6bf-726a-4413-85f8-40d9e0516a1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Save'])[3]</value>
      <webElementGuid>a758daee-f5ea-4a89-8b0f-b209069b23dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hospitalInfoForm']/ul/li[20]/div[2]/input</value>
      <webElementGuid>d5574734-a571-4fb0-9630-a2449382d346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[20]/div[2]/input</value>
      <webElementGuid>36e42b6b-75c6-4714-ae4c-1b6b6a89c692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>5025e9c0-cf37-4a22-a186-d08adc20af6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
