<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_samplegmail.com_addUserBtn</name>
   <tag></tag>
   <elementGuidId>7b09373a-74d5-4eb0-addf-0a949c524337</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addUserBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addUserBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add User&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>274c970b-1359-41ac-8894-32850bf5bb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addUserBtn</value>
      <webElementGuid>e44ff2a2-cbfd-4e6c-9ec2-ee0d9275f18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c233c4cf-aa83-4359-bd01-2b6c0ba08d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add User</value>
      <webElementGuid>da71926f-19c2-4ede-a447-bcb66080fa5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-primary</value>
      <webElementGuid>bf115f6c-dd36-4941-a4bd-52960f71698b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addUser()</value>
      <webElementGuid>1ecff78d-071b-4cdc-b8a3-0b5afd756bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addUserBtn&quot;)</value>
      <webElementGuid>50909807-22a1-4b2c-b4da-e20d472f97bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addUserBtn']</value>
      <webElementGuid>ddf8c058-343c-4aac-b9d4-e27f8dfcd92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='control-panel']/li[2]/div/p/input</value>
      <webElementGuid>b98f6e76-50ea-4fdb-9d47-3082144f0286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>44658079-ea70-48a8-ac67-a43810070740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addUserBtn' and @type = 'button']</value>
      <webElementGuid>81eaa38a-bd86-406d-8b90-18715f0d84ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
