<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hospital Email_Hospital.HospitalEmail</name>
   <tag></tag>
   <elementGuidId>86a8e7b9-420c-4b41-950c-25f23a1216c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Hospital_HospitalEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Hospital_HospitalEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Hospital Email&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd4200ec-ccae-4df4-9f6b-e17efa869d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-textbox k-textbox-md no-text-transform</value>
      <webElementGuid>0f8ede77-525c-43ef-859b-fce4a08e927d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8417a120-0019-443b-85d4-14ef14d9dab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-email</name>
      <type>Main</type>
      <value>The Hospital Email field is not a valid e-mail address.</value>
      <webElementGuid>4f6511f3-65a3-474b-bd35-cae41c18f0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Hospital Email field is required.</value>
      <webElementGuid>5147b2f3-9ac0-4ec9-84b0-42cb658f9b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Hospital_HospitalEmail</value>
      <webElementGuid>0d96f14b-10d8-46fd-8646-aadfb343fcde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Hospital.HospitalEmail</value>
      <webElementGuid>19e51576-eeb8-4472-8811-b2b6748bdf98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fee73a1-48d9-490f-b67f-cf7e097de48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Hospital_HospitalEmail&quot;)</value>
      <webElementGuid>3ff6b626-76fc-4ed9-9318-bcaab01ec0f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Hospital_HospitalEmail']</value>
      <webElementGuid>9e60f7e2-dbe4-4017-b809-259aec4e2cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hospitalInfoForm']/ul/li[4]/div/input</value>
      <webElementGuid>6074877f-049f-4134-aa18-c339e9513fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/ul/li[4]/div/input</value>
      <webElementGuid>3e66b235-8d5a-45d4-b2a5-a355ae2e5211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Hospital_HospitalEmail' and @name = 'Hospital.HospitalEmail' and @type = 'text']</value>
      <webElementGuid>b3971c0a-44e9-4df9-8cbc-f4ecb437e617</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
