<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_k-button k-primary</name>
   <tag></tag>
   <elementGuidId>14af2d12-d7f2-48c8-8d2a-7fdb5e3a2cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.k-button.k-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Connect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Connect&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32d5a58d-8af2-4cd2-9a29-8c73484beb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b56ac17a-08b7-4715-bb41-399d343b1edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Connect</value>
      <webElementGuid>3d27957b-7f24-4526-850b-d632866a883e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-primary</value>
      <webElementGuid>6f9bccad-1ed2-4e95-adf7-193fd7a49395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connectForm&quot;)/div[@class=&quot;connect-form&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;k-button k-primary&quot;]</value>
      <webElementGuid>26193686-6e74-491d-a6eb-7b8507cc6b30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Connect']</value>
      <webElementGuid>16d2d5dc-f209-42a2-b9c9-5156883c4c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='connectForm']/div/div[3]/input</value>
      <webElementGuid>adba708a-a1dc-4796-b97e-10855d67cb8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>92b20063-7337-4ef5-a35e-b18a1c3118f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>63f233cf-ab8c-40cf-af8a-76628c24a159</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
