<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Claims</name>
   <tag></tag>
   <elementGuidId>89ad1207-e26d-445b-b6ed-eb994da4987a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#claims-nav > a.flex-cell.commandbar-item-link.flex-grow > span.flex-grow.commandbar-item-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='claims-nav']/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Claims&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>23572dd7-c55b-4865-a5ad-60df933d3476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-grow commandbar-item-text</value>
      <webElementGuid>bc94cf44-4f21-415e-a4fd-8b9ad928c531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Claims</value>
      <webElementGuid>8217df0b-d0e7-40d2-9bba-06d29d06c92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;claims-nav&quot;)/a[@class=&quot;flex-cell commandbar-item-link flex-grow&quot;]/span[@class=&quot;flex-grow commandbar-item-text&quot;]</value>
      <webElementGuid>67b5785e-93e9-492a-9bf8-758bda3391b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='claims-nav']/a/span[2]</value>
      <webElementGuid>066585d0-9709-4718-9dc3-94a778a88fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::span[4]</value>
      <webElementGuid>d819f1c4-34f7-48da-a8d6-9b9a49d93d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient List'])[1]/following::span[8]</value>
      <webElementGuid>eae383b0-7a45-491e-86ef-b3cf68c8d337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim List'])[1]/preceding::span[4]</value>
      <webElementGuid>34a04c43-bcf2-4872-bccc-be2dc39675eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Claim'])[1]/preceding::span[8]</value>
      <webElementGuid>8634f7b4-7136-490d-8b37-3a06dd259d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Claims']/parent::*</value>
      <webElementGuid>196cc3e2-d77a-40e9-9a9d-944b6c858e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/span[2]</value>
      <webElementGuid>d09976d1-cb3d-4d7c-a5db-e6d2b6577605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Claims' or . = 'Claims')]</value>
      <webElementGuid>fe8dc01d-57d0-438d-b0d7-3e40ac39468e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
