<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_PatientReferred</name>
   <tag></tag>
   <elementGuidId>4d3eb24f-03d7-4606-a055-241415b1ad81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PatientReferred_N</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PatientReferred_N']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c292659-0b2d-4c12-b1cc-6fb932a10767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-radio</value>
      <webElementGuid>d2a5b6c7-f6b7-48e6-9333-24b97aa6b15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ae34fe74-16aa-48c8-95de-e745eb0d97c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PatientReferred_N</value>
      <webElementGuid>11d062ed-3a48-4bd5-b584-d1f5dc1952d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PatientReferred</value>
      <webElementGuid>92780ea0-108f-41bc-abc2-085e4b744169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>patientReferred_change()</value>
      <webElementGuid>779b25d3-773d-4e0e-85bb-0ec568749aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e94d74dd-cb3b-4322-881c-5dfac303f24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>eada7030-3216-4052-84ee-8ff6556e9aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PatientReferred_N&quot;)</value>
      <webElementGuid>1c6c84e4-67d7-42c8-b8e2-79774ae595a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PatientReferred_N']</value>
      <webElementGuid>76bba293-7b6e-4fcd-abc0-ffe64b12ed5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='healthcareinsinfoValidation']/input[3]</value>
      <webElementGuid>99f6344f-5679-44e1-9a9f-1373eb2eace2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>cf02397c-20fa-456d-8562-e2d7e4631c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PatientReferred_N' and @name = 'PatientReferred' and @type = 'radio']</value>
      <webElementGuid>96265a6d-9cf5-449b-a401-0a2d0f75173d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
