<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PatientType_Default_PatientType</name>
   <tag></tag>
   <elementGuidId>6801ce33-bd2c-4e28-831d-03a6f2b9896f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PatientType_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PatientType_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b179d95-35f0-4b40-9125-53b9596e9778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-radio</value>
      <webElementGuid>db1c1e0f-b7c3-491c-befd-566e3a4f4419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36711743-2aeb-426d-a4ce-ce664dfedc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PatientType_I</value>
      <webElementGuid>e9813016-b893-49fc-a375-d9f71d7f84ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PatientType</value>
      <webElementGuid>7885f931-3000-4244-b96c-082562bc0f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a1c2ba91-5a57-4f01-9b02-1ac7e0db658c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>I</value>
      <webElementGuid>aa3be23e-648e-47ac-bc82-0e8f13a77bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PatientType_I&quot;)</value>
      <webElementGuid>acefba80-4553-411c-9af3-c8d0e5d94347</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PatientType_I']</value>
      <webElementGuid>3492337e-5c1c-4e43-9a7e-0f5ea0084043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='patienttypeValidation']/input[2]</value>
      <webElementGuid>a96bab02-b2fd-4cf8-a3ac-92c502ee36ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input[2]</value>
      <webElementGuid>40d6aa8b-25ae-47c0-a21a-d1145fa73f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PatientType_I' and @name = 'PatientType' and @type = 'radio']</value>
      <webElementGuid>2d19d099-f79d-47b7-82cc-4d502d80e0a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
