<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please update the RVS Procedure Date(_50687d</name>
   <tag></tag>
   <elementGuidId>d3ed2192-08ce-45b8-b235-4430590f81c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dischargeDiagnosisForm > input.k-button.k-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7da8a77-d3fb-432b-b877-55d5ae986915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a203c96a-4923-4125-ba97-5238a653695c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>465903ce-d18b-48a8-9a87-50ffb42d3b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-primary</value>
      <webElementGuid>775a8177-0e22-44d4-9ca9-85def469df6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dischargeDiagnosisForm&quot;)/input[@class=&quot;k-button k-primary&quot;]</value>
      <webElementGuid>b494e6dd-e105-490b-b5ed-d3594c47ab35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Save']</value>
      <webElementGuid>020a1c82-ac01-4fb7-bee0-8636c1489a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dischargeDiagnosisForm']/input[3]</value>
      <webElementGuid>6bc5818a-5eb1-4d5d-ac0a-a3d1b62ae75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input[3]</value>
      <webElementGuid>5e322a85-d909-44a0-9541-23da9c2b0849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>2b042210-2da0-482f-a100-54dd04946282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
