<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_IsEmergency</name>
   <tag></tag>
   <elementGuidId>d11cd76b-b880-4f31-abd5-44f01d4a50a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IsEmergency_N</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IsEmergency_N']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9804bf4b-7145-4924-91f6-cbf7cac153be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-radio</value>
      <webElementGuid>767e1682-f1a1-4ab4-bbd0-2b0611c0e5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>731e71c7-d48d-428e-9e05-8c828aa59724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsEmergency_N</value>
      <webElementGuid>6a2448be-8446-4771-8291-9022d305bf22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsEmergency</value>
      <webElementGuid>a3e75377-e3b6-4d6e-9b0c-14c05fe376d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>da87f29d-00c1-41be-8823-36a022a453e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>6e5fc0f9-5fef-4fa9-95e7-cbb142bc2e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IsEmergency_N&quot;)</value>
      <webElementGuid>a962673a-5ca7-48b0-9130-bc45ea914ea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IsEmergency_N']</value>
      <webElementGuid>750e81be-d94b-404e-91d2-510563e13306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='patientconfinementinfoValidation']/input[3]</value>
      <webElementGuid>a5995feb-de5f-4eef-af83-93e3cd765eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input[3]</value>
      <webElementGuid>752be0a4-3073-4bc1-95d2-42952a3ce0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IsEmergency_N' and @name = 'IsEmergency' and @type = 'radio']</value>
      <webElementGuid>b9256471-6d6e-4024-a692-2597459523e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
