<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Right Eye IOL Expiry Date_SaveConfine_8606f5</name>
   <tag></tag>
   <elementGuidId>1dc67d3c-94b2-45d8-ab5b-1fdd3e9866e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SaveConfinementInfo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SaveConfinementInfo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f78570b-f7f3-422a-93ff-0600ec01206f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SaveConfinementInfo</value>
      <webElementGuid>fc61f05b-600d-4187-abe5-97cb81763bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>845b1dc9-d921-4c63-a96a-8f2984c6b41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>8dd7adbb-1217-4ab0-868a-2212aefc0dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-primary</value>
      <webElementGuid>2d1c9e76-7733-466b-a4da-7135c69cc7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SaveConfinementInfo&quot;)</value>
      <webElementGuid>0ef16a6c-8426-4c73-8cfa-f1fb9db6b411</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SaveConfinementInfo']</value>
      <webElementGuid>8e20139b-3a3b-4128-b3d0-1dc6478e80cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='confinementInfoForm']/p/input</value>
      <webElementGuid>49b46c82-c70c-41f3-bb68-c528f4764f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/p/input</value>
      <webElementGuid>785cb28f-11f9-44e2-8ccd-f72676972d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SaveConfinementInfo' and @type = 'submit']</value>
      <webElementGuid>a362a6a4-31aa-4a60-934d-7d7f875f1d64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
