<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please add at least one (1) Discharge_bd5a63</name>
   <tag></tag>
   <elementGuidId>3e4253e6-bd45-460e-b78b-4b063c456427</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.k-button.k-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Add Diagnosis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b356bd46-f599-4af4-b630-cfe5c98d99a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2c16c2f-aea3-4728-b44d-4440e0fc5e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add Diagnosis</value>
      <webElementGuid>0a37caba-db0e-4f66-aa92-5dc6a24097e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-primary</value>
      <webElementGuid>c5fd59a2-5653-42b9-bd43-3b390cb6c38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showDischargeDiagnosisForm()</value>
      <webElementGuid>ff8f75d2-c5bf-442d-ae98-a476466318dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dischargediagnosesForm&quot;)/div[1]/p[1]/input[@class=&quot;k-button k-primary&quot;]</value>
      <webElementGuid>fa63d32c-b979-44d7-b7df-0f3aeba71b30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Add Diagnosis']</value>
      <webElementGuid>c4316eea-55f7-428e-82be-0aabadd8e09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dischargediagnosesForm']/div/p/input</value>
      <webElementGuid>71046059-a001-4815-ab3a-58251394ed2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>e1cafc95-04ab-40d2-8674-5106dc7387c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>1c44bc8f-9322-4d99-b584-821dfcf1c47f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
