<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Discharge Diagnosis_DischargeDiagnosis</name>
   <tag></tag>
   <elementGuidId>c0fee247-5ba2-478b-b958-c7d8bee11ec8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DischargeDiagnosis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='DischargeDiagnosis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8915fa1f-b50b-441c-9379-7cd4ec2b80f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-textbox k-textbox-lg</value>
      <webElementGuid>d6883165-1be6-4d1b-b5af-a3d50fcbf3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>03f4731e-70f3-43e5-8eee-476f40a6ca89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The Discharge Diagnosis field can only have a maximum of 500 characters.</value>
      <webElementGuid>5d1a4f55-4068-443e-b628-913a0bfbf202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>5333ae86-2e73-475e-aba6-6d32f3bfa84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Discharge Diagnosis is required.</value>
      <webElementGuid>1226010c-65cb-46de-b683-93e8f56e71f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DischargeDiagnosis</value>
      <webElementGuid>46c28c89-5c1a-4102-a9fc-9d2f12c7b6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DischargeDiagnosis</value>
      <webElementGuid>2a7c08f1-c02f-4272-ad95-6c936f86117c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3a75a974-19a7-4ac8-975e-725076ea05d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DischargeDiagnosis&quot;)</value>
      <webElementGuid>a18fa3ab-6d45-460e-8057-416ffc9ca68c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='DischargeDiagnosis']</value>
      <webElementGuid>8236ec00-5735-4f5a-b421-4633f1dc08a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dischargeDiagnosisForm']/div/div/textarea</value>
      <webElementGuid>c2e4040c-0257-4c55-90e6-2609be8bd5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div/textarea</value>
      <webElementGuid>86a715d7-73be-485a-839e-9b6345263a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'DischargeDiagnosis' and @name = 'DischargeDiagnosis']</value>
      <webElementGuid>cb23251f-004d-475f-84ea-23b837351799</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
