<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Admission Diagnosis_AdmissionDiagnosis</name>
   <tag></tag>
   <elementGuidId>8ca56367-1e2e-44a1-8d8e-1fd701b26c0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AdmissionDiagnosis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='AdmissionDiagnosis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1f28785f-e209-42f2-a660-d7da335e7158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-textbox k-textbox-lg</value>
      <webElementGuid>0d61255b-7e96-480a-a534-a2c427ac419a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>a50fc11d-9fb1-4863-95a3-0359e2b0f034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ef51ab5-3084-4f4c-bbc6-d8e2cbc363dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The Admission Diagnosis field can only have a maximum of 500 character(s).</value>
      <webElementGuid>c5ea844e-d4ff-42fb-afc0-53ca732d001d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>1cda292a-61c3-41e3-b7b0-ca34c8eced2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Admission Diagnosis field is required.</value>
      <webElementGuid>ab617f1f-83f4-47c8-848c-f42d6de15aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AdmissionDiagnosis</value>
      <webElementGuid>94b48402-4c69-4381-8781-51264602e250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AdmissionDiagnosis</value>
      <webElementGuid>196ccca6-b336-4649-982b-d6cd08e577fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>81da3392-5614-4ed7-914f-0359eb9beb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AdmissionDiagnosis&quot;)</value>
      <webElementGuid>4577279c-7637-4d34-be5f-e273e7d45dcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='AdmissionDiagnosis']</value>
      <webElementGuid>793c6a26-0b0e-492b-a2bb-0dc4dee89ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admissiondiagnosisValidation']/textarea</value>
      <webElementGuid>9ddfe1ea-e9d7-44d9-9f29-99beb02c930a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/textarea</value>
      <webElementGuid>be41aae9-8c70-4834-9327-85725c97e9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'AdmissionDiagnosis' and @name = 'AdmissionDiagnosis']</value>
      <webElementGuid>246e75da-5d0e-4fd5-af0c-088eeeaf1cfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
